import type { Rarity, Species, SpeciesSeries } from "./types";

/**
 * 圖鑑門類（順序 = 顯示順序）：由 rarity 推導，唔使逐隻精靈加欄位。
 * 將來加聖獸／SSS 級：新增 rarity 值＋喺呢度加一條配置＋i18n `dex.category{Id}` 標籤即可。
 */
export const DEX_CATEGORIES: { id: string; rarities: readonly Rarity[] }[] = [
  { id: "standard", rarities: ["common", "rare", "epic", "legendary"] },
  { id: "basic", rarities: ["basic"] },
];

export const SERIES: SpeciesSeries[] = [
  {
    id: "chicken-rice",
    name: { en: "Chicken Rice Alliance", zh: "雞飯聯盟" },
    element: "water",
    flavor: "salty",
    foodOrigin: { en: "Hainanese Chicken Rice", zh: "海南雞飯" },
  },
  {
    id: "laksa",
    name: { en: "Noodle Clan", zh: "麵食家族" },
    element: "fire",
    flavor: "spicy",
    foodOrigin: { en: "Laksa", zh: "叻沙" },
  },
  {
    id: "bak-kut-teh",
    name: { en: "Bak Kut Teh Order", zh: "肉骨茶系" },
    element: "metal",
    flavor: "bitter",
    foodOrigin: { en: "Bak Kut Teh", zh: "肉骨茶" },
  },
  {
    id: "kueh",
    name: { en: "Kueh Dynasty", zh: "糕點系" },
    element: "earth",
    flavor: "sweet",
    foodOrigin: { en: "Kueh Lapis", zh: "九層糕" },
  },
  {
    id: "kaya",
    name: { en: "Kaya Legion", zh: "咖椰系" },
    element: "wood",
    flavor: "sour",
    foodOrigin: { en: "Kaya Toast", zh: "咖椰吐司" },
  },
  // ── 第一波擴充（每五行一系列試點）──
  {
    id: "chilli-crab",
    name: { en: "Chilli Crab Gang", zh: "辣蟹幫" },
    element: "water",
    flavor: "salty",
    foodOrigin: { en: "Chilli Crab", zh: "辣椒蟹" },
  },
  {
    id: "satay",
    name: { en: "Satay Legion", zh: "沙嗲軍團" },
    element: "fire",
    flavor: "spicy",
    foodOrigin: { en: "Satay", zh: "沙嗲" },
  },
  {
    id: "kopi",
    name: { en: "Kopi Society", zh: "咖啡烏會" },
    element: "metal",
    flavor: "bitter",
    foodOrigin: { en: "Kopi O", zh: "咖啡烏" },
  },
  {
    id: "chai-tow-kway",
    name: { en: "Carrot Cake Clan", zh: "菜頭粿門" },
    element: "earth",
    flavor: "sweet",
    foodOrigin: { en: "Chai Tow Kway", zh: "菜頭粿" },
  },
  {
    id: "rojak",
    name: { en: "Rojak Union", zh: "囉喏聯盟" },
    element: "wood",
    flavor: "sour",
    foodOrigin: { en: "Rojak", zh: "囉喏" },
  },
  {
    id: "oyster-omelette",
    name: { en: "Orh Luak Tribe", zh: "蠔煎眾" },
    element: "water",
    flavor: "salty",
    foodOrigin: { en: "Oyster Omelette", zh: "蠔煎" },
  },
  {
    id: "char-kway-teow",
    name: { en: "Wok Hei Sect", zh: "鑊氣幫" },
    element: "fire",
    flavor: "spicy",
    foodOrigin: { en: "Char Kway Teow", zh: "炒粿條" },
  },
  {
    id: "curry-puff",
    name: { en: "Curry Puff Order", zh: "咖喱卜團" },
    element: "metal",
    flavor: "bitter",
    foodOrigin: { en: "Curry Puff", zh: "咖喱卜" },
  },
  {
    id: "prata",
    name: { en: "Prata Tribe", zh: "煎餅族" },
    element: "earth",
    flavor: "sweet",
    foodOrigin: { en: "Roti Prata", zh: "印度煎餅" },
  },
  {
    id: "chendol",
    name: { en: "Chendol School", zh: "煎蕊派" },
    element: "wood",
    flavor: "sour",
    foodOrigin: { en: "Chendol", zh: "煎蕊" },
  },
  // ── 原材料層（basic：單階、最弱、隨處可見）──
  {
    id: "chilli-baby",
    name: { en: "Chilli Baby", zh: "辣椒仔" },
    element: "fire",
    flavor: "spicy",
    foodOrigin: { en: "Chilli Padi", zh: "辣椒" },
  },
  {
    id: "garlic-guard",
    name: { en: "Garlic Guard", zh: "蒜頭衛兵" },
    element: "metal",
    flavor: "spicy",
    foodOrigin: { en: "Garlic", zh: "蒜頭" },
  },
  {
    id: "lemongrass-swordsman",
    name: { en: "Lemongrass Swordsman", zh: "香茅劍客" },
    element: "wood",
    flavor: "sour",
    foodOrigin: { en: "Lemongrass", zh: "香茅" },
  },
  {
    id: "riceball-baby",
    name: { en: "Riceball Baby", zh: "飯團寶寶" },
    element: "earth",
    flavor: "sweet",
    foodOrigin: { en: "Rice Ball", zh: "飯團" },
  },
  {
    id: "vermicelli-sprite",
    name: { en: "Vermicelli Sprite", zh: "米粉精靈" },
    element: "water",
    flavor: "salty",
    foodOrigin: { en: "Rice Vermicelli", zh: "米粉" },
  },
  {
    id: "egg-guard",
    name: { en: "Egg Guard", zh: "蛋蛋守衛" },
    element: "earth",
    flavor: "salty",
    foodOrigin: { en: "Egg", zh: "雞蛋" },
  },
  {
    id: "shrimp-hopper",
    name: { en: "Shrimp Hopper", zh: "蝦仔跳跳" },
    element: "water",
    flavor: "sweet",
    foodOrigin: { en: "Fresh Shrimp", zh: "鮮蝦" },
  },
  {
    id: "coconut-jelly",
    name: { en: "Coconut Jelly", zh: "椰漿啫喱" },
    element: "wood",
    flavor: "sweet",
    foodOrigin: { en: "Coconut Milk", zh: "椰漿" },
  },
  {
    id: "ice-kachang-christmas-dragon",
    name: { en: "Ice Kachang Dragons", zh: "冰豆龍系" },
    foodOrigin: { en: "Ice Kachang", zh: "紅豆冰" },
    element: "water",
    flavor: "sweet",
  },

  {
    id: "wanton-mee",
    name: { en: "Wanton Mee", zh: "雲吞麵" },
    element: "metal",
    flavor: "salty",
    foodOrigin: { en: "Wanton Mee", zh: "雲吞麵" },
  },
];

export const SPECIES: Species[] = [
  // ── 雞飯聯盟（水/鹹）──────────────────────────────
  {
    id: "oily-rice-chick",
    seriesId: "chicken-rice",
    stage: 1,
    name: { en: "Oily Rice Chick", zh: "油飯雞仔" },
    element: "water",
    flavor: "salty",
    rarity: "common",
    foodOrigin: { en: "Hainanese Chicken Rice", zh: "海南雞飯" },
    description: {
      en: "A fluffy chick born from fragrant chicken rice. Smells faintly of pandan.",
      zh: "由香噴噴雞油飯孵出嘅小雞，隱約有斑蘭香。",
    },
    baseStats: { hp: 45, attack: 12, defense: 10, speed: 14 },
    skills: [
      {
        id: "rice-peck",
        name: { en: "Rice Peck", zh: "米粒啄擊" },
        description: { en: "Pecks with grains of oily rice.", zh: "用油飯米粒連續啄擊。" },
        power: 1.0,
        cooldown: 0,
      },
      {
        id: "oily-heal",
        name: { en: "Oily Rice Heal", zh: "油飯治癒" },
        description: { en: "Restores 30% HP to the team.", zh: "為全隊回復 30% HP。" },
        power: 0,
        cooldown: 3,
        healPercent: 0.3,
      },
    ],
    evolvesTo: "silky-chicken-warrior",
    evolutionRequirement: { items: { "chicken-oil-essence": 5 }, checkinCentres: 2 },
    modelUrl: "/models/oily-rice-chick.glb",
    modelHeightM: 0.3,
    animated: true,
    rigLite: true,
    // facing-lock: 2026-08-01 player-back enemy-face
    modelYaw: -Math.PI / 2,
  },
  {
    id: "silky-chicken-warrior",
    seriesId: "chicken-rice",
    stage: 2,
    name: { en: "Silky Chicken Warrior", zh: "滑雞武者" },
    element: "water",
    flavor: "salty",
    rarity: "rare",
    foodOrigin: { en: "Hainanese Chicken Rice", zh: "海南雞飯" },
    description: {
      en: "Trained in the art of the poached blade. Its skin glistens like silk.",
      zh: "修行白斬刀法嘅武者，雞皮滑如絲綢。",
    },
    baseStats: { hp: 70, attack: 22, defense: 18, speed: 20 },
    skills: [
      {
        id: "poached-blade",
        name: { en: "Poached Blade", zh: "白斬刀法" },
        description: { en: "A clean, precise strike.", zh: "乾淨利落嘅一刀。" },
        power: 1.3,
        cooldown: 1,
      },
      {
        id: "ginger-splash",
        name: { en: "Ginger Splash", zh: "薑蓉飛濺" },
        description: { en: "Splashes hot ginger sauce.", zh: "潑灑熱辣薑蓉。" },
        power: 1.6,
        cooldown: 2,
      },
    ],
    evolvesTo: "hainan-chicken-god",
    evolutionRequirement: {
      items: { "chicken-oil-essence": 10, "hainan-secret-recipe": 1 },
      checkinCentres: 5,
    },
    modelUrl: "/models/silky-chicken-warrior.glb",
    modelHeightM: 0.45,
    animated: true,
    // verify5：+π/2 露出正面；保持 0（背向鏡頭）
    // facing-lock: 2026-08-01 player-back enemy-face
    modelYaw: 0,
  },
  {
    id: "hainan-chicken-god",
    seriesId: "chicken-rice",
    stage: 3,
    name: { en: "Hainan Chicken God", zh: "海南雞神" },
    element: "water",
    flavor: "salty",
    rarity: "epic",
    foodOrigin: { en: "Hainanese Chicken Rice", zh: "海南雞飯" },
    description: {
      en: "The deity of the national dish. One bow of its golden cape blesses a whole hawker centre.",
      zh: "國民美食之神，金色披風一揮，庇佑成個小販中心。",
    },
    baseStats: { hp: 100, attack: 34, defense: 28, speed: 26 },
    skills: [
      {
        id: "golden-rice-storm",
        name: { en: "Golden Rice Storm", zh: "黃金飯暴" },
        description: { en: "Summons a storm of golden rice.", zh: "召喚黃金油飯風暴。" },
        power: 2.0,
        cooldown: 2,
      },
      {
        id: "chilli-sauce-cannon",
        name: { en: "Chilli Sauce Cannon", zh: "辣椒醬炮" },
        description: { en: "Fires signature chilli sauce.", zh: "發射招牌辣椒醬。" },
        power: 1.5,
        cooldown: 1,
      },
    ],
    evolvesTo: null,
    evolutionRequirement: null,
    modelUrl: "/models/hainan-chicken-god.glb",
    modelHeightM: 0.6,
    animated: true,
    rigLite: true,
    // facing-lock: 2026-08-01 player-back enemy-face
    modelYaw: -Math.PI / 2,
  },

  // ── 麵食家族（火/辣）──────────────────────────────
  {
    id: "little-laksa",
    seriesId: "laksa",
    stage: 1,
    name: { en: "Little Laksa", zh: "叻沙仔" },
    element: "fire",
    flavor: "spicy",
    rarity: "common",
    foodOrigin: { en: "Laksa", zh: "叻沙" },
    description: {
      en: "A tiny shrimp spirit wearing a laksa leaf hat. Mildly spicy when startled.",
      zh: "戴住叻沙葉帽嘅小蝦精，嚇親會微微辣。",
    },
    baseStats: { hp: 42, attack: 15, defense: 8, speed: 16 },
    skills: [
      {
        id: "broth-splash",
        name: { en: "Broth Splash", zh: "湯底潑濺" },
        description: { en: "Splashes hot laksa broth.", zh: "潑灑滾燙叻沙湯。" },
        power: 1.0,
        cooldown: 0,
      },
      {
        id: "coconut-shield",
        name: { en: "Coconut Shield", zh: "椰漿護盾" },
        description: { en: "Thick coconut milk softens blows.", zh: "濃椰漿卸走攻擊。" },
        power: 0,
        cooldown: 3,
        healPercent: 0.2,
      },
    ],
    evolvesTo: "laksa-warrior",
    evolutionRequirement: { items: { "shrimp-shell-shard": 5 }, checkinCentres: 2 },
    modelUrl: "/models/little-laksa.glb",
    modelHeightM: 0.3,
    animated: true,
    // verify5：+π/2 仍背敵；改 -π/2
    // facing-lock: 2026-08-01 player-back enemy-face
    modelYaw: -Math.PI / 2,
  },
  {
    id: "laksa-warrior",
    seriesId: "laksa",
    stage: 2,
    name: { en: "Laksa Warrior", zh: "叻沙武士" },
    element: "fire",
    flavor: "spicy",
    rarity: "rare",
    foodOrigin: { en: "Laksa", zh: "叻沙" },
    description: {
      en: "Armoured in shrimp shell plate, cloaked in a laksa leaf. Its claws simmer with spice.",
      zh: "披蝦殼鎧甲、戴叻沙葉披風，一雙蝦鉗辣力沸騰。",
    },
    baseStats: { hp: 68, attack: 26, defense: 16, speed: 22 },
    skills: [
      {
        id: "shell-claw",
        name: { en: "Shell Claw", zh: "蝦殼鉗擊" },
        description: { en: "Crushes with armoured claws.", zh: "用裝甲蝦鉗夾擊。" },
        power: 1.3,
        cooldown: 1,
      },
      {
        id: "spicy-surge",
        name: { en: "Spicy Surge", zh: "辣浪翻騰" },
        description: { en: "A wave of chilli-laden broth.", zh: "掀起辣椒湯浪。" },
        power: 1.6,
        cooldown: 2,
      },
    ],
    evolvesTo: "laksa-dragon",
    evolutionRequirement: {
      items: { "shrimp-shell-shard": 10, "laksa-soul": 1 },
      checkinCentres: 5,
    },
    modelUrl: "/models/laksa-warrior.glb",
    modelHeightM: 0.5,
    animated: true,
    // yaw sweep：0 背向鏡頭對敵；舊 -π/2 側身
    // facing-lock: 2026-08-01 player-back enemy-face
    modelYaw: 0,
  },
  {
    id: "laksa-dragon",
    seriesId: "laksa",
    stage: 3,
    name: { en: "Laksa Dragon", zh: "叻沙龍" },
    element: "fire",
    flavor: "spicy",
    rarity: "legendary",
    foodOrigin: { en: "Laksa", zh: "叻沙" },
    description: {
      en: "A dragon forged in boiling laksa broth. Its tail flame never goes out.",
      zh: "喺沸騰叻沙湯中誕生嘅神龍，尾焰永不熄滅。",
    },
    baseStats: { hp: 105, attack: 40, defense: 24, speed: 30 },
    skills: [
      {
        id: "spice-inferno",
        name: { en: "Spice Inferno", zh: "香料烈焰" },
        description: { en: "Breathes a torrent of burning spice.", zh: "噴出灼熱香料烈焰。" },
        power: 2.2,
        cooldown: 2,
      },
      {
        id: "dragon-noodle-whip",
        name: { en: "Dragon Noodle Whip", zh: "龍鬚麵鞭" },
        description: { en: "Lashes with thick vermicelli.", zh: "用粗米粉長鞭抽擊。" },
        power: 1.5,
        cooldown: 1,
      },
    ],
    evolvesTo: null,
    evolutionRequirement: null,
    modelUrl: "/models/laksa-dragon.glb",
    modelHeightM: 0.65,
    animated: true,
    // yaw sweep：0 背向鏡頭；舊 -π/2 側身扭頸
    // facing-lock: 2026-08-01 player-back enemy-face
    modelYaw: 0,
  },

  // ── 肉骨茶系（金/苦）──────────────────────────────
  {
    id: "bkt-cub",
    seriesId: "bak-kut-teh",
    stage: 1,
    name: { en: "Bak Kut Cub", zh: "肉骨仔" },
    element: "metal",
    flavor: "bitter",
    rarity: "common",
    foodOrigin: { en: "Bak Kut Teh", zh: "肉骨茶" },
    description: {
      en: "A panda cub wearing a pork-rib helmet, raised on peppery herbal soup.",
      zh: "戴住排骨頭盔嘅熊貓仔，飲胡椒藥膳湯大。",
    },
    baseStats: { hp: 50, attack: 11, defense: 14, speed: 10 },
    skills: [
      {
        id: "rib-bonk",
        name: { en: "Rib Bonk", zh: "排骨敲擊" },
        description: { en: "Bonks with a pork rib.", zh: "用排骨敲落去。" },
        power: 1.0,
        cooldown: 0,
      },
      {
        id: "herbal-sip",
        name: { en: "Herbal Sip", zh: "藥膳補湯" },
        description: { en: "Sips soup to restore 25% HP.", zh: "飲啖湯回復 25% HP。" },
        power: 0,
        cooldown: 3,
        healPercent: 0.25,
      },
    ],
    evolvesTo: "bkt-warrior",
    evolutionRequirement: { items: { "spice-essence": 5 }, checkinCentres: 2 },
    modelUrl: "/models/bkt-cub.glb",
    modelHeightM: 0.35,
    animated: true,
    rigLite: true,
    // facing-lock: 2026-08-01 player-back enemy-face
    modelYaw: -Math.PI / 2,
  },
  {
    id: "bkt-warrior",
    seriesId: "bak-kut-teh",
    stage: 2,
    name: { en: "Bak Kut Warrior", zh: "骨茶武士" },
    element: "metal",
    flavor: "bitter",
    rarity: "rare",
    foodOrigin: { en: "Bak Kut Teh", zh: "肉骨茶" },
    description: {
      en: "A samurai panda in rib-bone armour, wielding a youtiao club and bowl shield.",
      zh: "披骨甲嘅熊貓武士，手持油條棍同湯碗盾。",
    },
    baseStats: { hp: 78, attack: 20, defense: 24, speed: 14 },
    skills: [
      {
        id: "youtiao-strike",
        name: { en: "Youtiao Strike", zh: "油條重擊" },
        description: { en: "Swings a crispy youtiao club.", zh: "揮動香脆油條棍。" },
        power: 1.3,
        cooldown: 1,
      },
      {
        id: "pepper-guard",
        name: { en: "Pepper Guard", zh: "胡椒鐵壁" },
        description: { en: "Peppery aura raises defense.", zh: "胡椒氣場提升防禦。" },
        power: 0.8,
        cooldown: 2,
      },
    ],
    evolvesTo: "bkt-grandmaster",
    evolutionRequirement: { items: { "spice-essence": 10 }, checkinCentres: 5 },
    modelUrl: "/models/bkt-warrior.glb",
    modelHeightM: 0.5,
    animated: true,
    // facing-lock: 2026-08-01 player-back enemy-face
    modelYaw: Math.PI / 2,
  },
  {
    id: "bkt-grandmaster",
    seriesId: "bak-kut-teh",
    stage: 3,
    name: { en: "Bak Kut Grandmaster", zh: "骨茶宗師" },
    element: "metal",
    flavor: "bitter",
    rarity: "epic",
    foodOrigin: { en: "Bak Kut Teh", zh: "肉骨茶" },
    description: {
      en: "In golden herb-forged armour, the grandmaster guards every claypot in the land.",
      zh: "身穿藥膳金甲嘅宗師，守護全島每一煲肉骨茶。",
    },
    baseStats: { hp: 115, attack: 30, defense: 36, speed: 18 },
    skills: [
      {
        id: "garlic-meteor",
        name: { en: "Garlic Meteor", zh: "蒜頭流星" },
        description: { en: "Rains whole garlic cloves.", zh: "召喚蒜頭流星雨。" },
        power: 1.9,
        cooldown: 2,
      },
      {
        id: "claypot-slam",
        name: { en: "Claypot Slam", zh: "砂鍋猛擊" },
        description: { en: "Slams down a scalding claypot.", zh: "用滾燙砂鍋猛砸。" },
        power: 1.6,
        cooldown: 1,
      },
    ],
    evolvesTo: null,
    evolutionRequirement: null,
    modelUrl: "/models/bkt-grandmaster.glb",
    // facing-lock: 2026-08-01 player-back enemy-face
    modelYaw: 0,
    modelHeightM: 0.65,
    animated: true,
  },

  // ── 糕點系（土/甜）──────────────────────────────
  {
    id: "tutu-sprite",
    seriesId: "kueh",
    stage: 1,
    name: { en: "Tutu Sprite", zh: "嘟嘟糕精" },
    element: "earth",
    flavor: "sweet",
    rarity: "common",
    foodOrigin: { en: "Kueh Tutu", zh: "嘟嘟糕" },
    description: {
      en: "A steamy little sprite dusted with coconut. Squeaks 'tutu!' when happy.",
      zh: "灑滿椰絲嘅蒸氣小精靈，開心會叫「嘟嘟」。",
    },
    baseStats: { hp: 44, attack: 12, defense: 11, speed: 13 },
    skills: [
      {
        id: "coconut-puff",
        name: { en: "Coconut Puff", zh: "椰絲噴發" },
        description: { en: "Puffs a cloud of coconut.", zh: "噴出椰絲雲。" },
        power: 1.0,
        cooldown: 0,
      },
      {
        id: "steam-veil",
        name: { en: "Steam Veil", zh: "蒸氣面紗" },
        description: { en: "Hides in sweet steam, healing 20% HP.", zh: "藏身甜蒸氣，回復 20% HP。" },
        power: 0,
        cooldown: 3,
        healPercent: 0.2,
      },
    ],
    evolvesTo: "lapis-queen",
    evolutionRequirement: { items: { "colour-layer": 5 }, checkinCentres: 2 },
    modelUrl: "/models/tutu-sprite.glb",
    // HQ remake 2026-08-03：嘟嘟糕系統一軟糕 DNA；Meshy 422→Tripo rigLite
    // facing-lock: 2026-08-02 player-back enemy-face
    modelYaw: 0,
    modelHeightM: 0.28,
    animated: true,
    rigLite: true,


  },
  {
    id: "lapis-queen",
    seriesId: "kueh",
    stage: 2,
    name: { en: "Lapis Queen", zh: "九層糕后" },
    element: "earth",
    flavor: "sweet",
    rarity: "rare",
    foodOrigin: { en: "Kueh Lapis", zh: "九層糕" },
    description: {
      en: "Nine rainbow layers form her gown. Each layer holds a different sweetness.",
      zh: "九層彩虹化作華服，每層有唔同嘅甜。",
    },
    baseStats: { hp: 72, attack: 21, defense: 20, speed: 17 },
    skills: [
      {
        id: "layer-slice",
        name: { en: "Layer Slice", zh: "分層切擊" },
        description: { en: "Slices with a rainbow edge.", zh: "用彩虹利刃切擊。" },
        power: 1.3,
        cooldown: 1,
      },
      {
        id: "sticky-trap",
        name: { en: "Sticky Trap", zh: "黏糕陷阱" },
        description: { en: "Sticky kueh slows the foe.", zh: "黏韌糕體困住敵人。" },
        power: 1.5,
        cooldown: 2,
      },
    ],
    evolvesTo: "pastry-queen",
    evolutionRequirement: {
      items: { "colour-layer": 10, "condensed-milk-can": 3 },
      checkinCentres: 5,
    },
    modelUrl: "/models/lapis-queen.glb",
    // HQ remake 2026-08-03：同系軟糕面＋層糕甲；Tripo→Meshy fullRig
    // facing-lock: 2026-08-02 player-back enemy-face
    modelYaw: Math.PI / 2,
    modelHeightM: 0.5,
    animated: true,


  },
  {
    id: "pastry-queen",
    seriesId: "kueh",
    stage: 3,
    name: { en: "Pastry Sovereign", zh: "糕點女王" },
    element: "earth",
    flavor: "sweet",
    rarity: "epic",
    foodOrigin: { en: "Kueh Lapis", zh: "九層糕" },
    description: {
      en: "Ruler of every kueh stall on the island. Her crown is a tower of ondeh-ondeh.",
      zh: "統領全島糕點檔嘅女王，皇冠係一座椰糖球塔。",
    },
    baseStats: { hp: 108, attack: 32, defense: 30, speed: 22 },
    skills: [
      {
        id: "gula-melaka-burst",
        name: { en: "Gula Melaka Burst", zh: "椰糖爆漿" },
        description: { en: "Explodes molten palm sugar.", zh: "爆發熔岩椰糖漿。" },
        power: 2.0,
        cooldown: 2,
      },
      {
        id: "royal-decree",
        name: { en: "Royal Decree", zh: "女王詔令" },
        description: { en: "Commands a kueh barrage.", zh: "號令糕點齊射。" },
        power: 1.5,
        cooldown: 1,
      },
    ],
    evolvesTo: null,
    evolutionRequirement: null,
    modelUrl: "/models/pastry-queen.glb",
    // HQ remake 2026-08-03：同系軟糕面＋糕點帝；Tripo→Meshy fullRig
    // facing-lock: 2026-08-02 player-back enemy-face
    modelYaw: 0,
    modelHeightM: 0.62,
    animated: true,
  },

  // ── 咖椰系（木/酸）──────────────────────────────
  {
    id: "kaya-blob",
    seriesId: "kaya",
    stage: 1,
    name: { en: "Kaya Blob", zh: "咖央仔" },
    element: "wood",
    flavor: "sour",
    rarity: "common",
    foodOrigin: { en: "Kaya Toast", zh: "咖椰吐司" },
    description: {
      en: "A wobbly green blob of kaya wearing a pandan-leaf hat.",
      zh: "戴斑蘭葉帽、搖搖晃晃嘅綠色咖椰精。",
    },
    baseStats: { hp: 46, attack: 13, defense: 9, speed: 15 },
    skills: [
      {
        id: "jam-splat",
        name: { en: "Jam Splat", zh: "醬汁飛濺" },
        description: { en: "Flings sticky kaya jam.", zh: "拋出黏笠咖椰醬。" },
        power: 1.0,
        cooldown: 0,
      },
      {
        id: "pandan-breeze",
        name: { en: "Pandan Breeze", zh: "斑蘭清風" },
        description: { en: "A soothing breeze heals 20% HP.", zh: "斑蘭香風回復 20% HP。" },
        power: 0,
        cooldown: 3,
        healPercent: 0.2,
      },
    ],
    evolvesTo: "kaya-warrior",
    evolutionRequirement: { items: { "kaya-drop": 5 }, checkinCentres: 2 },
    modelUrl: "/models/kaya-blob.glb",
    modelHeightM: 0.25,
    animated: true,
    rigLite: true,
    // facing-lock: 2026-08-01 player-back enemy-face
    modelYaw: -Math.PI / 2,
  },
  {
    id: "kaya-warrior",
    seriesId: "kaya",
    stage: 2,
    name: { en: "Kaya Samurai", zh: "咖央武士" },
    element: "wood",
    flavor: "sour",
    rarity: "rare",
    foodOrigin: { en: "Kaya Toast", zh: "咖椰吐司" },
    description: {
      en: "Armoured in jade-green kaya plate, wielding a toast hammer and butter shield.",
      zh: "披翠綠咖椰鎧甲，手持吐司錘同牛油盾。",
    },
    baseStats: { hp: 66, attack: 24, defense: 17, speed: 21 },
    skills: [
      {
        id: "toast-hammer",
        name: { en: "Toast Hammer", zh: "吐司重錘" },
        description: { en: "Smashes with crispy toast.", zh: "用香脆吐司錘擊。" },
        power: 1.3,
        cooldown: 1,
      },
      {
        id: "butter-slick",
        name: { en: "Butter Slick", zh: "牛油滑步" },
        description: { en: "Slides on butter to strike fast.", zh: "踩住牛油高速突擊。" },
        power: 1.6,
        cooldown: 2,
      },
    ],
    evolvesTo: "kaya-dragon",
    evolutionRequirement: { items: { "kaya-drop": 10, "condensed-milk-can": 2 }, checkinCentres: 5 },
    modelUrl: "/models/kaya-warrior.glb",

    // HQ remake 2026-08-02：Tripo→Meshy fullRig（modelYaw 待 facing-lock）
    // facing-lock: 2026-08-02 player-back enemy-face

    modelYaw: 0,
    modelHeightM: 0.5,
    animated: true,

  },
  {
    id: "kaya-dragon",
    seriesId: "kaya",
    stage: 3,
    name: { en: "Kaya Dragon", zh: "咖央聖龍" },
    element: "wood",
    flavor: "sour",
    rarity: "epic",
    foodOrigin: { en: "Kaya Toast", zh: "咖椰吐司" },
    description: {
      en: "A holy dragon wreathed in emerald phantom flame, guardian of every kopitiam breakfast.",
      zh: "身纏翡翠幻火嘅聖龍，守護每一份咖啡店早餐。",
    },
    baseStats: { hp: 102, attack: 36, defense: 26, speed: 28 },
    skills: [
      {
        id: "phantom-flame",
        name: { en: "Phantom Flame", zh: "翡翠幻火" },
        description: { en: "Emerald flames that never burn toast.", zh: "永遠唔會燒燶吐司嘅翡翠火。" },
        power: 2.1,
        cooldown: 2,
      },
      {
        id: "soft-egg-orb",
        name: { en: "Soft Egg Orb", zh: "半熟蛋彈" },
        description: { en: "Hurls a wobbly half-boiled egg.", zh: "投擲搖晃嘅半熟蛋。" },
        power: 1.5,
        cooldown: 1,
      },
    ],
    evolvesTo: null,
    evolutionRequirement: null,
    modelUrl: "/models/kaya-dragon.glb",

    // HQ remake 2026-08-02：Tripo→Meshy fullRig（modelYaw 待 facing-lock）
    // facing-lock: 2026-08-02 player-back enemy-face

    modelYaw: 0,
    modelHeightM: 0.65,
    animated: true,
  },

  // ── 辣蟹幫（水/鹹）──────────────────────────────
  {
    id: "chilli-crablet",
    seriesId: "chilli-crab",
    stage: 1,
    name: { en: "Chilli Crablet", zh: "辣蟹仔" },
    element: "water",
    flavor: "salty",
    rarity: "common",
    foodOrigin: { en: "Chilli Crab", zh: "辣椒蟹" },
    description: {
      en: "A baby crab born in a wok of chilli gravy. Blows spicy bubbles when excited.",
      zh: "喺辣醬鑊入面出世嘅蟹 BB，興奮會吹辣泡泡。",
    },
    baseStats: { hp: 46, attack: 13, defense: 12, speed: 12 },
    skills: [
      {
        id: "bubble-spit",
        name: { en: "Bubble Spit", zh: "泡泡醬沫" },
        description: { en: "Spits bubbly chilli gravy.", zh: "吐出咕嘟咕嘟嘅辣醬泡。" },
        power: 1.0,
        cooldown: 0,
      },
      {
        id: "mantou-recovery",
        name: { en: "Mantou Recovery", zh: "饅頭回氣" },
        description: { en: "Dips fried mantou to heal 25% HP.", zh: "炸饅頭撈醬，回復 25% HP。" },
        power: 0,
        cooldown: 3,
        healPercent: 0.25,
      },
    ],
    evolvesTo: "crab-claw-warrior",
    evolutionRequirement: { items: { "crab-claw-shard": 5 }, checkinCentres: 2 },
    modelUrl: "/models/chilli-crablet.glb",
    modelHeightM: 0.28,
    animated: true,
    // 還原 674de88 醬頭大鉗版（Tripo rigLite）
    rigLite: true,
    // facing-lock: 2026-08-02 player-back enemy-face
    modelYaw: 0,
  },
  {
    id: "crab-claw-warrior",
    seriesId: "chilli-crab",
    stage: 2,
    name: { en: "Crab Claw Warrior", zh: "辣蟹武士" },
    element: "water",
    flavor: "salty",
    rarity: "rare",
    foodOrigin: { en: "Chilli Crab", zh: "辣椒蟹" },
    description: {
      en: "Its shell hardened by simmering gravy. One claw cracks, the other crushes.",
      zh: "蟹殼喺辣醬滾煮中煉成鎧甲，一鉗破防一鉗粉碎。",
    },
    baseStats: { hp: 72, attack: 24, defense: 20, speed: 16 },
    skills: [
      {
        id: "claw-crush",
        name: { en: "Claw Crush", zh: "巨鉗粉碎" },
        description: { en: "Crushes with an armoured claw.", zh: "用重甲巨鉗夾碎目標。" },
        power: 1.3,
        cooldown: 1,
      },
      {
        id: "sauce-whirl",
        name: { en: "Sauce Whirl", zh: "醬濤翻滾" },
        description: { en: "Whips up a whirl of chilli gravy.", zh: "捲起辣醬漩渦潑向敵人。" },
        power: 1.6,
        cooldown: 2,
      },
    ],
    evolvesTo: "chilli-crab-king",
    evolutionRequirement: {
      items: { "crab-claw-shard": 10, "chilli-gravy-jar": 1 },
      checkinCentres: 5,
    },
    modelUrl: "/models/crab-claw-warrior.glb",
    // facing-lock: 2026-08-01 player-back enemy-face
    modelYaw: 0,
    modelHeightM: 0.5,
    animated: true,
  },
  {
    id: "chilli-crab-king",
    seriesId: "chilli-crab",
    stage: 3,
    name: { en: "Chilli Crab King", zh: "辣椒蟹王" },
    element: "water",
    flavor: "salty",
    rarity: "legendary",
    foodOrigin: { en: "Chilli Crab", zh: "辣椒蟹" },
    description: {
      en: "The national-dish monarch. Where its claws point, a tsunami of gravy follows.",
      zh: "國菜之王，巨鉗一指，辣醬海嘯隨之而至。",
    },
    baseStats: { hp: 108, attack: 38, defense: 30, speed: 24 },
    skills: [
      {
        id: "chilli-tsunami",
        name: { en: "Chilli Tsunami", zh: "辣醬海嘯" },
        description: { en: "Summons a tidal wave of chilli gravy.", zh: "召喚滔天辣醬巨浪。" },
        power: 2.1,
        cooldown: 2,
      },
      {
        id: "golden-mantou-barrage",
        name: { en: "Golden Mantou Barrage", zh: "金饅頭連炮" },
        description: { en: "Fires volleys of fried mantou.", zh: "連環發射金黃炸饅頭。" },
        power: 1.5,
        cooldown: 1,
      },
    ],
    evolvesTo: null,
    evolutionRequirement: null,
    modelUrl: "/models/chilli-crab-king.glb",
    // facing-lock: 2026-08-01 player-back enemy-face
    modelYaw: 0,
    modelHeightM: 0.65,
    animated: true,
  },

  // ── 沙嗲軍團（火/辣）──────────────────────────────
  {
    id: "satay-skewerling",
    seriesId: "satay",
    stage: 1,
    name: { en: "Satay Skewerling", zh: "沙嗲仔" },
    element: "fire",
    flavor: "spicy",
    rarity: "common",
    foodOrigin: { en: "Satay", zh: "沙嗲" },
    description: {
      en: "A tiny skewer soldier marinated in turmeric. Dreams of the great charcoal fire.",
      zh: "醃透黃薑嘅串燒小兵，日日夢想住上炭爐。",
    },
    baseStats: { hp: 43, attack: 15, defense: 9, speed: 16 },
    skills: [
      {
        id: "skewer-jab",
        name: { en: "Skewer Jab", zh: "竹籤突刺" },
        description: { en: "Jabs with a bamboo skewer.", zh: "用竹籤快速突刺。" },
        power: 1.0,
        cooldown: 0,
      },
      {
        id: "ketupat-rest",
        name: { en: "Ketupat Rest", zh: "馬來米糕休整" },
        description: { en: "Snacks on ketupat to heal 20% HP.", zh: "食啖馬來米糕，回復 20% HP。" },
        power: 0,
        cooldown: 3,
        healPercent: 0.2,
      },
    ],
    evolvesTo: "satay-warrior",
    evolutionRequirement: { items: { "bamboo-skewer": 5 }, checkinCentres: 2 },
    modelUrl: "/models/satay-skewerling.glb",
    modelHeightM: 0.3,
    animated: true,
    rigLite: true,
    // facing-lock: 2026-08-01 player-back enemy-face
    modelYaw: -Math.PI / 2,
  },
  {
    id: "satay-warrior",
    seriesId: "satay",
    stage: 2,
    name: { en: "Satay Warrior", zh: "沙嗲武士" },
    element: "fire",
    flavor: "spicy",
    rarity: "rare",
    foodOrigin: { en: "Satay", zh: "沙嗲" },
    description: {
      en: "A grill-hardened lancer cloaked in peanut sauce, wielding three skewers at once.",
      zh: "炭火煉成嘅長槍手，披花生醬戰袍，一手揸三串。",
    },
    baseStats: { hp: 67, attack: 26, defense: 15, speed: 23 },
    skills: [
      {
        id: "charcoal-grill",
        name: { en: "Charcoal Grill", zh: "炭火串燒" },
        description: { en: "Breathes searing charcoal heat.", zh: "噴出炙熱炭火氣浪。" },
        power: 1.3,
        cooldown: 1,
      },
      {
        id: "triple-skewer",
        name: { en: "Triple Skewer", zh: "三串連擊" },
        description: { en: "Strikes thrice with skewers.", zh: "三串齊發連環刺擊。" },
        power: 1.6,
        cooldown: 2,
      },
    ],
    evolvesTo: "satay-flame-emperor",
    evolutionRequirement: {
      items: { "bamboo-skewer": 10, "charcoal-ember": 1 },
      checkinCentres: 5,
    },
    modelUrl: "/models/satay-warrior.glb",

    // HQ remake 2026-08-02：Tripo→Meshy fullRig（modelYaw 待 facing-lock）
    // facing-lock: 2026-08-02 player-back enemy-face

    modelYaw: 0,
    modelHeightM: 0.5,
    animated: true,

  },
  {
    id: "satay-flame-emperor",
    seriesId: "satay",
    stage: 3,
    name: { en: "Satay Flame Emperor", zh: "沙嗲炎帝" },
    element: "fire",
    flavor: "spicy",
    rarity: "epic",
    foodOrigin: { en: "Satay", zh: "沙嗲" },
    description: {
      en: "Emperor of the open flame. One fan of its wing and a hundred skewers ignite.",
      zh: "明火之帝，翼一撥，百串齊燃。",
    },
    baseStats: { hp: 100, attack: 39, defense: 23, speed: 30 },
    skills: [
      {
        id: "hundred-skewer-storm",
        name: { en: "Hundred Skewer Storm", zh: "百串燎原" },
        description: { en: "Rains a hundred flaming skewers.", zh: "百枝火串漫天落下。" },
        power: 2.1,
        cooldown: 2,
      },
      {
        id: "peanut-sauce-flood",
        name: { en: "Peanut Sauce Flood", zh: "花生醬洪流" },
        description: { en: "Unleashes a torrent of peanut sauce.", zh: "傾瀉香濃花生醬洪流。" },
        power: 1.5,
        cooldown: 1,
      },
    ],
    evolvesTo: null,
    evolutionRequirement: null,
    modelUrl: "/models/satay-flame-emperor.glb",
    modelHeightM: 0.65,
    animated: true,
    // yaw sweep 968a49：-90 面向對手；+90 背敵；0 側身含糊
    // facing-lock: 2026-08-01 player-back enemy-face
    modelYaw: -Math.PI / 2,
  },

  // ── 咖啡烏會（金/苦）──────────────────────────────
  {
    id: "kopi-bean",
    seriesId: "kopi",
    stage: 1,
    name: { en: "Kopi Bean", zh: "咖啡仔" },
    element: "metal",
    flavor: "bitter",
    rarity: "common",
    foodOrigin: { en: "Kopi O", zh: "咖啡烏" },
    description: {
      en: "A dark-roasted bean sprite that never sleeps. Smells of butter and sugar.",
      zh: "永遠唔眼瞓嘅深焙豆精靈，帶住牛油焦糖香。",
    },
    baseStats: { hp: 44, attack: 12, defense: 11, speed: 15 },
    skills: [
      {
        id: "bean-toss",
        name: { en: "Bean Toss", zh: "咖啡豆投擲" },
        description: { en: "Flings roasted kopi beans.", zh: "拋出深焙咖啡豆。" },
        power: 1.0,
        cooldown: 0,
      },
      {
        id: "kopi-sip",
        name: { en: "Kopi Sip", zh: "提神一啖" },
        description: { en: "A hot sip restores 25% HP.", zh: "呷啖熱咖啡，回復 25% HP。" },
        power: 0,
        cooldown: 3,
        healPercent: 0.25,
      },
    ],
    evolvesTo: "kopi-sock-warrior",
    evolutionRequirement: { items: { "roasted-bean": 5 }, checkinCentres: 2 },
    modelUrl: "/models/kopi-bean.glb",
    modelHeightM: 0.26,
    animated: true,
    rigLite: true,
    // facing-lock: 2026-08-01 player-back enemy-face
    modelYaw: -Math.PI / 2,
  },
  {
    id: "kopi-sock-warrior",
    seriesId: "kopi",
    stage: 2,
    name: { en: "Kopi Sock Warrior", zh: "咖啡武士" },
    element: "metal",
    flavor: "bitter",
    rarity: "rare",
    foodOrigin: { en: "Kopi O", zh: "咖啡烏" },
    description: {
      en: "Master of the long pour. Its kopi sock swings like a meteor hammer.",
      zh: "拉茶長沖嘅高手，咖啡袋一甩就係流星錘。",
    },
    baseStats: { hp: 70, attack: 23, defense: 19, speed: 20 },
    skills: [
      {
        id: "sock-swing",
        name: { en: "Sock Swing", zh: "咖啡袋重甩" },
        description: { en: "Swings a loaded kopi sock.", zh: "掄起裝滿咖啡渣嘅布袋重擊。" },
        power: 1.3,
        cooldown: 1,
      },
      {
        id: "steam-scald",
        name: { en: "Steam Scald", zh: "滾水燙擊" },
        description: { en: "Splashes boiling kopi water.", zh: "潑出滾燙沖茶熱水。" },
        power: 1.6,
        cooldown: 2,
      },
    ],
    evolvesTo: "kopi-o-emperor",
    evolutionRequirement: {
      items: { "roasted-bean": 10, "heirloom-kopi-sock": 1 },
      checkinCentres: 5,
    },
    modelUrl: "/models/kopi-sock-warrior.glb",

    // HQ remake 2026-08-02：Tripo→Meshy fullRig（modelYaw 待 facing-lock）
    // facing-lock: 2026-08-02 player-back enemy-face

    modelYaw: 0,
    modelHeightM: 0.48,
    animated: true,

  },
  {
    id: "kopi-o-emperor",
    seriesId: "kopi",
    stage: 3,
    name: { en: "Kopi O Emperor", zh: "咖啡烏皇" },
    element: "metal",
    flavor: "bitter",
    rarity: "epic",
    foodOrigin: { en: "Kopi O", zh: "咖啡烏" },
    description: {
      en: "Sovereign of every kopitiam dawn. Its cape is a waterfall of black gold.",
      zh: "統領全島咖啡店晨光嘅帝皇，披風係一匹黑金瀑布。",
    },
    baseStats: { hp: 104, attack: 33, defense: 32, speed: 26 },
    skills: [
      {
        id: "black-gold-waterfall",
        name: { en: "Black Gold Waterfall", zh: "黑金瀑布" },
        description: { en: "Pours a waterfall of scalding kopi.", zh: "自高空傾瀉滾燙黑金咖啡。" },
        power: 2.0,
        cooldown: 2,
      },
      {
        id: "caffeine-rush",
        name: { en: "Caffeine Rush", zh: "咖啡因狂熱" },
        description: { en: "A jolt of caffeine sharpens every strike.", zh: "咖啡因上腦，招招見紅。" },
        power: 1.5,
        cooldown: 1,
      },
    ],
    evolvesTo: null,
    evolutionRequirement: null,
    modelUrl: "/models/kopi-o-emperor.glb",


    // HQ remake 2026-08-02：Tripo→Meshy fullRig（modelYaw 待 facing-lock）
    // facing-lock: 2026-08-02 player-back enemy-face

    modelYaw: 0,
    modelHeightM: 0.62,
    animated: true,

  },

  // ── 菜頭粿門（土/甜）──────────────────────────────
  {
    id: "radish-cubie",
    seriesId: "chai-tow-kway",
    stage: 1,
    name: { en: "Radish Cubie", zh: "菜頭仔" },
    element: "earth",
    flavor: "sweet",
    rarity: "common",
    foodOrigin: { en: "Chai Tow Kway", zh: "菜頭粿" },
    description: {
      en: "A squishy white radish-cake cube, still waiting for its first griddle lesson.",
      zh: "軟腍腍嘅白粿粒，仲未上過第一堂鐵板課。",
    },
    baseStats: { hp: 50, attack: 11, defense: 14, speed: 10 },
    skills: [
      {
        id: "cube-tumble",
        name: { en: "Cube Tumble", zh: "粿粒翻滾" },
        description: { en: "Tumbles into the foe as a cube.", zh: "成舊粿咁碌埋去撞。" },
        power: 1.0,
        cooldown: 0,
      },
      {
        id: "radish-juice",
        name: { en: "Radish Juice", zh: "菜頭甜汁" },
        description: { en: "Sweet radish juice heals 25% HP.", zh: "清甜蘿蔔汁回復 25% HP。" },
        power: 0,
        cooldown: 3,
        healPercent: 0.25,
      },
    ],
    evolvesTo: "carrot-cake-warrior",
    evolutionRequirement: { items: { "white-radish": 5 }, checkinCentres: 2 },
    modelUrl: "/models/radish-cubie.glb",
    modelHeightM: 0.26,
    animated: true,
    rigLite: true,
    // facing-lock: 2026-08-01 player-back enemy-face
    modelYaw: -Math.PI / 2,
  },
  {
    id: "carrot-cake-warrior",
    seriesId: "chai-tow-kway",
    stage: 2,
    name: { en: "Carrot Cake Warrior", zh: "菜頭粿武士" },
    element: "earth",
    flavor: "sweet",
    rarity: "rare",
    foodOrigin: { en: "Chai Tow Kway", zh: "菜頭粿" },
    description: {
      en: "Trained on a scorching griddle, its egg-crust armour is crisp outside, soft inside.",
      zh: "喺灼熱鐵板上修行，蛋香脆甲外脆內軟。",
    },
    baseStats: { hp: 76, attack: 21, defense: 24, speed: 13 },
    skills: [
      {
        id: "griddle-press",
        name: { en: "Griddle Press", zh: "鐵板煎壓" },
        description: { en: "Slams down like a hot griddle.", zh: "化身滾熱鐵板壓落去。" },
        power: 1.3,
        cooldown: 1,
      },
      {
        id: "egg-crust-slam",
        name: { en: "Egg Crust Slam", zh: "蛋香脆擊" },
        description: { en: "Strikes with a crispy egg crust.", zh: "用香脆蛋皮猛擊。" },
        power: 1.6,
        cooldown: 2,
      },
    ],
    evolvesTo: "black-white-cake-king",
    evolutionRequirement: {
      items: { "white-radish": 10, "dark-sweet-sauce": 1 },
      checkinCentres: 5,
    },
    modelUrl: "/models/carrot-cake-warrior.glb",

    // HQ remake 2026-08-02：Tripo→Meshy fullRig（modelYaw 待 facing-lock）
    // facing-lock: 2026-08-02 player-back enemy-face

    modelYaw: 0,
    modelHeightM: 0.48,
    animated: true,

  },
  {
    id: "black-white-cake-king",
    seriesId: "chai-tow-kway",
    stage: 3,
    name: { en: "Black & White Cake King", zh: "黑白粿王" },
    element: "earth",
    flavor: "sweet",
    rarity: "epic",
    foodOrigin: { en: "Chai Tow Kway", zh: "菜頭粿" },
    description: {
      en: "Master of both styles — dark sweet soy and pale crisp. Two woks, one king.",
      zh: "黑甜白脆兩派歸一，雙鑊在手，粿界稱王。",
    },
    baseStats: { hp: 112, attack: 31, defense: 34, speed: 18 },
    skills: [
      {
        id: "black-white-duet",
        name: { en: "Black & White Duet", zh: "黑白雙煎" },
        description: { en: "Twin wok strikes, dark then light.", zh: "黑白雙鑊連環轟擊。" },
        power: 2.0,
        cooldown: 2,
      },
      {
        id: "sweet-sauce-quake",
        name: { en: "Sweet Sauce Quake", zh: "甜醬地震" },
        description: { en: "Dark sweet sauce shakes the earth.", zh: "黑甜醬傾瀉，震動地面。" },
        power: 1.5,
        cooldown: 1,
      },
    ],
    evolvesTo: null,
    evolutionRequirement: null,
    modelUrl: "/models/black-white-cake-king.glb",
    animated: true,
    // HQ remake 2026-08-02：Tripo rigLite（補齊先前失敗嘅骨架／動畫）
    rigLite: true,
    // facing-lock: 2026-08-02 player-back enemy-face
    modelYaw: -Math.PI / 2,
    modelHeightM: 0.62,
  },

  // ── 囉喏聯盟（木/酸）──────────────────────────────
  {
    id: "rojak-tot",
    seriesId: "rojak",
    stage: 1,
    name: { en: "Rojak Tot", zh: "囉喏仔" },
    element: "wood",
    flavor: "sour",
    rarity: "common",
    foodOrigin: { en: "Rojak", zh: "囉喏" },
    description: {
      en: "A mixed-up little sprite of fruit and jicama. 'Rojak' is its way of life.",
      zh: "雜果加沙葛撈埋一齊嘅小精靈，「撈」就係佢嘅人生。",
    },
    baseStats: { hp: 45, attack: 13, defense: 10, speed: 15 },
    skills: [
      {
        id: "pineapple-jab",
        name: { en: "Pineapple Jab", zh: "菠蘿刺擊" },
        description: { en: "Pokes with a pineapple wedge.", zh: "用菠蘿角篤過去。" },
        power: 1.0,
        cooldown: 0,
      },
      {
        id: "peanut-dust",
        name: { en: "Peanut Dust", zh: "花生碎療癒" },
        description: { en: "A sprinkle of peanut heals 20% HP.", zh: "灑一把花生碎，回復 20% HP。" },
        power: 0,
        cooldown: 3,
        healPercent: 0.2,
      },
    ],
    evolvesTo: "rojak-warrior",
    evolutionRequirement: { items: { "haeko-paste": 5 }, checkinCentres: 2 },
    modelUrl: "/models/rojak-tot.glb",
    // HQ remake 2026-08-01：Tripo rigLite（Meshy 422）
    rigLite: true,
    // facing-lock: 2026-08-01 player-back enemy-face
    modelYaw: -Math.PI / 2,
    modelHeightM: 0.28,
    animated: true,


  },
  {
    id: "rojak-warrior",
    seriesId: "rojak",
    stage: 2,
    name: { en: "Rojak Warrior", zh: "囉喏武士" },
    element: "wood",
    flavor: "sour",
    rarity: "rare",
    foodOrigin: { en: "Rojak", zh: "囉喏" },
    description: {
      en: "Wields a whip of black haeko and a jicama shield. Every battle is a good toss.",
      zh: "揸黑蝦膏長鞭同沙葛圓盾，每一場架都係一場撈。",
    },
    baseStats: { hp: 68, attack: 24, defense: 17, speed: 21 },
    skills: [
      {
        id: "haeko-whip",
        name: { en: "Haeko Whip", zh: "蝦膏黑鞭" },
        description: { en: "Lashes with sticky black haeko.", zh: "黑蝦膏長鞭黐住就抽。" },
        power: 1.3,
        cooldown: 1,
      },
      {
        id: "jicama-shield-bash",
        name: { en: "Jicama Shield Bash", zh: "沙葛盾擊" },
        description: { en: "Bashes with a crunchy jicama shield.", zh: "用爽脆沙葛盾撞擊。" },
        power: 1.6,
        cooldown: 2,
      },
    ],
    evolvesTo: "rojak-king",
    evolutionRequirement: {
      items: { "haeko-paste": 10, "crushed-peanut": 1 },
      checkinCentres: 5,
    },
    modelUrl: "/models/rojak-warrior.glb",
    animated: true,

    // HQ remake 2026-08-02：Tripo→Meshy fullRig（modelYaw 待 facing-lock）
    // facing-lock: 2026-08-02 player-back enemy-face

    modelYaw: 0,
    modelHeightM: 0.5,
  },
  {
    id: "rojak-king",
    seriesId: "rojak",
    stage: 3,
    name: { en: "Rojak King", zh: "囉喏王" },
    element: "wood",
    flavor: "sour",
    rarity: "epic",
    foodOrigin: { en: "Rojak", zh: "囉喏" },
    description: {
      en: "King of a hundred flavours. Its crown mixes fruit, dough and sauce into one storm.",
      zh: "百味之王，皇冠上果、脆、醬共冶一爐，撈出風暴。",
    },
    baseStats: { hp: 103, attack: 35, defense: 27, speed: 27 },
    skills: [
      {
        id: "hundred-flavour-vortex",
        name: { en: "Hundred Flavour Vortex", zh: "百味漩渦" },
        description: { en: "A cyclone of fruit and youtiao.", zh: "雜果油條捲成龍捲風。" },
        power: 2.0,
        cooldown: 2,
      },
      {
        id: "black-sauce-deluge",
        name: { en: "Black Sauce Deluge", zh: "黑醬傾盆" },
        description: { en: "Pours down sticky haeko rain.", zh: "黑蝦膏傾盆而下。" },
        power: 1.5,
        cooldown: 1,
      },
    ],
    evolvesTo: null,
    evolutionRequirement: null,
    modelUrl: "/models/rojak-king.glb",
    animated: true,

    // HQ remake 2026-08-02：Tripo→Meshy fullRig（modelYaw 待 facing-lock）
    // facing-lock: 2026-08-02 player-back enemy-face

    modelYaw: 0,
    modelHeightM: 0.63,
  },

  // ── 蠔煎眾（水/鹹）──────────────────────────────
  {
    id: "little-orh-luak",
    seriesId: "oyster-omelette",
    stage: 1,
    name: { en: "Little Orh Luak", zh: "蠔煎仔" },
    element: "water",
    flavor: "salty",
    rarity: "common",
    foodOrigin: { en: "Oyster Omelette", zh: "蠔煎" },
    description: {
      en: "A wobbly starch-batter sprite hugging a baby oyster. Slippery when nervous.",
      zh: "攬住蠔仔嘅粉漿小精靈，一緊張就滑潺潺。",
    },
    baseStats: { hp: 47, attack: 12, defense: 11, speed: 14 },
    skills: [
      {
        id: "starch-flick",
        name: { en: "Starch Flick", zh: "粉漿彈射" },
        description: { en: "Flicks gooey starch batter.", zh: "彈出黏韌粉漿。" },
        power: 1.0,
        cooldown: 0,
      },
      {
        id: "egg-blanket",
        name: { en: "Egg Blanket", zh: "蛋被治癒" },
        description: { en: "Wraps in fluffy egg, healing 25% HP.", zh: "冚張蛋被瞓陣，回復 25% HP。" },
        power: 0,
        cooldown: 3,
        healPercent: 0.25,
      },
    ],
    evolvesTo: "omelette-warrior",
    evolutionRequirement: { items: { "plump-oyster": 5 }, checkinCentres: 2 },
    modelUrl: "/models/little-orh-luak.glb",
    animated: true,
    rigLite: true,
    // facing-lock: 2026-08-01 player-back enemy-face
    modelYaw: -Math.PI / 2,
    modelHeightM: 0.27,
  },
  {
    id: "omelette-warrior",
    seriesId: "oyster-omelette",
    stage: 2,
    name: { en: "Omelette Warrior", zh: "蠔煎武者" },
    element: "water",
    flavor: "salty",
    rarity: "rare",
    foodOrigin: { en: "Oyster Omelette", zh: "蠔煎" },
    description: {
      en: "Forged on a blazing flat wok. Its crispy-edged egg cloak flips faster than the eye.",
      zh: "猛火鐵板煉出嚟嘅武者，脆邊蛋披風快過眼瞓。",
    },
    baseStats: { hp: 71, attack: 23, defense: 18, speed: 21 },
    skills: [
      {
        id: "sizzle-flip",
        name: { en: "Sizzle Flip", zh: "鑊氣翻面" },
        description: { en: "A blazing-fast omelette flip strike.", zh: "疾速翻面，蛋邊掃擊。" },
        power: 1.3,
        cooldown: 1,
      },
      {
        id: "oyster-pearl-shot",
        name: { en: "Oyster Pearl Shot", zh: "珍珠蠔彈" },
        description: { en: "Fires plump oysters like pearls.", zh: "肥美蠔仔當珍珠咁射。" },
        power: 1.6,
        cooldown: 2,
      },
    ],
    evolvesTo: "oyster-immortal",
    evolutionRequirement: { items: { "plump-oyster": 10 }, checkinCentres: 5 },
    // 還原有骨架版本（Tripo rig，7 clips 揮煎鏟）：rigLite 令 runtime strip 掉 root
    modelUrl: "/models/omelette-warrior.glb",

    // HQ remake 2026-08-02：Tripo→Meshy fullRig（modelYaw 待 facing-lock）
    // facing-lock: 2026-08-02 player-back enemy-face

    modelYaw: 0,
    modelHeightM: 0.48,
    animated: true,


  },
  {
    id: "oyster-immortal",
    seriesId: "oyster-omelette",
    stage: 3,
    name: { en: "Oyster Immortal", zh: "蠔煎仙" },
    element: "water",
    flavor: "salty",
    rarity: "epic",
    foodOrigin: { en: "Oyster Omelette", zh: "蠔煎" },
    description: {
      en: "An immortal wreathed in vinegar mist. Every wave of its sleeve is a tide of golden egg.",
      zh: "身纏酸醋銀霧嘅仙人，衣袖一揮就係金蛋浪潮。",
    },
    baseStats: { hp: 104, attack: 34, defense: 28, speed: 26 },
    skills: [
      {
        id: "tidal-omelette",
        name: { en: "Tidal Omelette", zh: "蛋海狂潮" },
        description: { en: "Summons a golden tide of egg.", zh: "捲起金黃蛋海狂潮。" },
        power: 2.0,
        cooldown: 2,
      },
      {
        id: "vinegar-mist",
        name: { en: "Vinegar Mist", zh: "酸醋銀霧" },
        description: { en: "A sharp mist that stings the eyes.", zh: "噴出醒神酸醋霧。" },
        power: 1.5,
        cooldown: 1,
      },
    ],
    evolvesTo: null,
    evolutionRequirement: null,
    // 還原有骨架版本（Meshy rig，7 clips 揮法杖，同 bkt-warrior 同款人形骨架）
    modelUrl: "/models/oyster-immortal.glb",

    // HQ remake 2026-08-02：Tripo→Meshy fullRig（modelYaw 待 facing-lock）
    // facing-lock: 2026-08-02 player-back enemy-face

    modelYaw: 0,
    modelHeightM: 0.62,
    animated: true,

  },

  // ── 鑊氣幫（火/辣）──────────────────────────────
  {
    id: "kway-teow-kid",
    seriesId: "char-kway-teow",
    stage: 1,
    name: { en: "Kway Teow Kid", zh: "粿條仔" },
    element: "fire",
    flavor: "spicy",
    rarity: "common",
    foodOrigin: { en: "Char Kway Teow", zh: "炒粿條" },
    description: {
      en: "A ribbon-bodied noodle sprite practising wok-flips with a toy spatula.",
      zh: "麵帶身形嘅粿條精，日日用玩具鑊鏟練拋鑊。",
    },
    baseStats: { hp: 43, attack: 14, defense: 9, speed: 17 },
    skills: [
      {
        id: "flat-noodle-lash",
        name: { en: "Flat Noodle Lash", zh: "粿條抽擊" },
        description: { en: "Lashes with a flat rice noodle.", zh: "用扁身粿條抽擊。" },
        power: 1.0,
        cooldown: 0,
      },
      {
        id: "lard-crisp-boost",
        name: { en: "Lard Crisp Boost", zh: "豬油渣滋補" },
        description: { en: "Crunchy lard crisps heal 20% HP.", zh: "香脆豬油渣回復 20% HP。" },
        power: 0,
        cooldown: 3,
        healPercent: 0.2,
      },
    ],
    evolvesTo: "kway-teow-warrior",
    evolutionRequirement: { items: { "lard-crisp": 5 }, checkinCentres: 2 },
    modelUrl: "/models/kway-teow-kid.glb",
    modelHeightM: 0.29,
    animated: true,
    rigLite: true,
    // facing-lock: 2026-08-01 player-back enemy-face
    modelYaw: -Math.PI / 2,
  },
  {
    id: "kway-teow-warrior",
    seriesId: "char-kway-teow",
    stage: 2,
    name: { en: "Kway Teow Warrior", zh: "粿條武士" },
    element: "fire",
    flavor: "spicy",
    rarity: "rare",
    foodOrigin: { en: "Char Kway Teow", zh: "炒粿條" },
    description: {
      en: "Cultivates the inner art of wok hei. Its dark soy armour gleams with charred sweetness.",
      zh: "修煉鑊氣內功，黑甜醬鎧甲透住焦香。",
    },
    baseStats: { hp: 66, attack: 26, defense: 16, speed: 22 },
    skills: [
      {
        id: "wok-toss",
        name: { en: "Wok Toss", zh: "拋鑊翻炒" },
        description: { en: "Tosses the foe like fried noodles.", zh: "當炒粉咁拋起對手。" },
        power: 1.3,
        cooldown: 1,
      },
      {
        id: "cockle-bomb",
        name: { en: "Cockle Bomb", zh: "血蚶炸彈" },
        description: { en: "Lobs juicy cockles that burst.", zh: "掟出爆漿血蚶。" },
        power: 1.6,
        cooldown: 2,
      },
    ],
    evolvesTo: "wok-hei-god",
    evolutionRequirement: {
      items: { "lard-crisp": 10, "wok-hei-spark": 1 },
      checkinCentres: 5,
    },
    modelUrl: "/models/kway-teow-warrior.glb",
    modelHeightM: 0.5,
    animated: true,
    rigLite: true,
    // facing-lock: 2026-08-01 player-back enemy-face
    modelYaw: -Math.PI / 2,
  },
  {
    id: "wok-hei-god",
    seriesId: "char-kway-teow",
    stage: 3,
    name: { en: "Wok Hei God", zh: "鑊氣神" },
    element: "fire",
    flavor: "spicy",
    rarity: "epic",
    foodOrigin: { en: "Char Kway Teow", zh: "炒粿條" },
    description: {
      en: "The deity of breath-of-the-wok. Its cape of noodles ripples with living flame.",
      zh: "鑊氣之神，粿條披風翻動如活火。",
    },
    baseStats: { hp: 101, attack: 39, defense: 24, speed: 29 },
    skills: [
      {
        id: "wok-hei-blast",
        name: { en: "Wok Hei Blast", zh: "鑊氣爆發" },
        description: { en: "Erupts the breath of the wok.", zh: "引爆灼熱鑊氣。" },
        power: 2.1,
        cooldown: 2,
      },
      {
        id: "dark-soy-tide",
        name: { en: "Dark Soy Tide", zh: "黑甜醬浪" },
        description: { en: "A sweet dark tide of soy.", zh: "掀起黑甜醬油巨浪。" },
        power: 1.5,
        cooldown: 1,
      },
    ],
    evolvesTo: null,
    evolutionRequirement: null,
    modelUrl: "/models/wok-hei-god.glb",
    // facing-lock: 2026-08-01 player-back enemy-face
    modelYaw: 0,
    modelHeightM: 0.64,
    animated: true,
  },

  // ── 咖喱卜團（金/苦）──────────────────────────────
  {
    id: "curry-puffling",
    seriesId: "curry-puff",
    stage: 1,
    name: { en: "Curry Puffling", zh: "咖喱卜仔" },
    element: "metal",
    flavor: "bitter",
    rarity: "common",
    foodOrigin: { en: "Curry Puff", zh: "咖喱卜" },
    description: {
      en: "A crescent-shaped pastry sprite. Its spiral crimped edge is its pride.",
      zh: "半月形酥皮小精靈，最自豪係條螺旋花邊。",
    },
    baseStats: { hp: 45, attack: 12, defense: 13, speed: 13 },
    skills: [
      {
        id: "crust-flick",
        name: { en: "Crust Flick", zh: "酥皮碎擊" },
        description: { en: "Flicks crispy pastry shards.", zh: "彈出香脆酥皮碎。" },
        power: 1.0,
        cooldown: 0,
      },
      {
        id: "potato-cushion",
        name: { en: "Potato Cushion", zh: "薯仔軟墊" },
        description: { en: "Soft curry potato heals 25% HP.", zh: "咖喱薯仔軟墊回復 25% HP。" },
        power: 0,
        cooldown: 3,
        healPercent: 0.25,
      },
    ],
    evolvesTo: "curry-puff-warrior",
    evolutionRequirement: { items: { "golden-crust-flake": 5 }, checkinCentres: 2 },
    modelUrl: "/models/curry-puffling.glb",
    modelHeightM: 0.27,
    animated: true,
    rigLite: true,
    // facing-lock: 2026-08-01 player-back enemy-face
    modelYaw: -Math.PI / 2,
  },
  {
    id: "curry-puff-warrior",
    seriesId: "curry-puff",
    stage: 2,
    name: { en: "Curry Puff Warrior", zh: "咖喱卜武士" },
    element: "metal",
    flavor: "bitter",
    rarity: "rare",
    foodOrigin: { en: "Curry Puff", zh: "咖喱卜" },
    description: {
      en: "Armoured in layered golden crust. Molten curry runs beneath every plate.",
      zh: "千層金酥皮做甲，甲下流動住滾燙咖喱。",
    },
    baseStats: { hp: 72, attack: 22, defense: 22, speed: 17 },
    skills: [
      {
        id: "spiral-crust-cutter",
        name: { en: "Spiral Crust Cutter", zh: "螺旋酥皮刃" },
        description: { en: "Slices with a spiral crimped edge.", zh: "用螺旋花邊迴旋切擊。" },
        power: 1.3,
        cooldown: 1,
      },
      {
        id: "curry-burst",
        name: { en: "Curry Burst", zh: "咖喱噴發" },
        description: { en: "Bursts hot curry filling.", zh: "爆出熱辣咖喱餡。" },
        power: 1.6,
        cooldown: 2,
      },
    ],
    evolvesTo: "golden-puff-sovereign",
    evolutionRequirement: { items: { "golden-crust-flake": 10 }, checkinCentres: 5 },
    modelUrl: "/models/curry-puff-warrior.glb",
    modelHeightM: 0.48,
    animated: true,
    // Tripo root：要 stripRoot，唔然 idle 搶 lookAt
    rigLite: true,
    // yaw sweep 968a49：0 背向鏡頭；180 正面（錯）
    // facing-lock: 2026-08-01 player-back enemy-face
    modelYaw: 0,
  },
  {
    id: "golden-puff-sovereign",
    seriesId: "curry-puff",
    stage: 3,
    name: { en: "Golden Puff Sovereign", zh: "咖喱卜尊" },
    element: "metal",
    flavor: "bitter",
    rarity: "epic",
    foodOrigin: { en: "Curry Puff", zh: "咖喱卜" },
    description: {
      en: "A thousand golden layers, one sovereign. Its blades are baked, its heart is molten.",
      zh: "千層酥金歸一尊，刃係焗出嚟，心係熔岩咖喱。",
    },
    baseStats: { hp: 106, attack: 33, defense: 33, speed: 22 },
    skills: [
      {
        id: "thousand-layer-blades",
        name: { en: "Thousand Layer Blades", zh: "千層酥刃" },
        description: { en: "Rains razor-thin crust blades.", zh: "千層酥刃漫天飛舞。" },
        power: 2.0,
        cooldown: 2,
      },
      {
        id: "molten-curry-cannon",
        name: { en: "Molten Curry Cannon", zh: "熔岩咖喱炮" },
        description: { en: "Fires a shot of molten curry.", zh: "轟出熔岩級咖喱彈。" },
        power: 1.5,
        cooldown: 1,
      },
    ],
    evolvesTo: null,
    evolutionRequirement: null,
    modelUrl: "/models/golden-puff-sovereign.glb",
    modelHeightM: 0.62,
    animated: true,
    rigLite: true,
    // facing-lock: 2026-08-01 player-back enemy-face
    modelYaw: -Math.PI / 2,
  },

  // ── 煎餅族（土/甜）──────────────────────────────
  {
    id: "prata-pup",
    seriesId: "prata",
    stage: 1,
    name: { en: "Prata Pup", zh: "煎餅仔" },
    element: "earth",
    flavor: "sweet",
    rarity: "common",
    foodOrigin: { en: "Roti Prata", zh: "印度煎餅" },
    description: {
      en: "A doughy baby elephant spirit. Practises prata-flipping with its trunk.",
      zh: "麵團身嘅小象精，用象鼻練習拋餅。",
    },
    baseStats: { hp: 49, attack: 11, defense: 14, speed: 11 },
    skills: [
      {
        id: "dough-slap",
        name: { en: "Dough Slap", zh: "麵團拍打" },
        description: { en: "Slaps with stretchy dough.", zh: "用彈性麵團拍落去。" },
        power: 1.0,
        cooldown: 0,
      },
      {
        id: "ghee-shine",
        name: { en: "Ghee Shine", zh: "酥油滋潤" },
        description: { en: "Glossy ghee heals 25% HP.", zh: "香濃酥油滋潤，回復 25% HP。" },
        power: 0,
        cooldown: 3,
        healPercent: 0.25,
      },
    ],
    evolvesTo: "prata-warrior",
    evolutionRequirement: { items: { "stretchy-dough": 5 }, checkinCentres: 2 },
    modelUrl: "/models/prata-pup.glb",
    modelHeightM: 0.3,
    animated: true,
    // 同系列 Meshy Hips；yawfix +90° 先睇到餅形，0° 會扁糊
    // facing-lock: 2026-08-01 player-back enemy-face
    modelYaw: Math.PI / 2,
  },
  {
    id: "prata-warrior",
    seriesId: "prata",
    stage: 2,
    name: { en: "Prata Warrior", zh: "煎餅武士" },
    element: "earth",
    flavor: "sweet",
    rarity: "rare",
    foodOrigin: { en: "Roti Prata", zh: "印度煎餅" },
    description: {
      en: "An elephant warrior whose prata discs spin like chakrams. Crispy folds, soft heart.",
      zh: "煎餅飛輪喺手嘅大象武士，外脆內軟。",
    },
    baseStats: { hp: 75, attack: 21, defense: 23, speed: 15 },
    skills: [
      {
        id: "flip-spin-throw",
        name: { en: "Flip Spin Throw", zh: "拋餅迴旋" },
        description: { en: "Hurls a spinning prata disc.", zh: "擲出迴旋煎餅飛輪。" },
        power: 1.3,
        cooldown: 1,
      },
      {
        id: "crispy-fold-strike",
        name: { en: "Crispy Fold Strike", zh: "摺疊脆擊" },
        description: { en: "Strikes with a folded crispy edge.", zh: "用摺疊脆邊猛擊。" },
        power: 1.6,
        cooldown: 2,
      },
    ],
    evolvesTo: "prata-sky-elephant",
    evolutionRequirement: {
      items: { "stretchy-dough": 10, "ghee-jar": 1 },
      checkinCentres: 5,
    },
    modelUrl: "/models/prata-warrior.glb",
    modelHeightM: 0.52,
    animated: true,
    // facing-lock: 2026-08-01 player-back enemy-face
    modelYaw: Math.PI / 2,
  },
  {
    id: "prata-sky-elephant",
    seriesId: "prata",
    stage: 3,
    name: { en: "Prata Sky Elephant", zh: "飛餅神象" },
    element: "earth",
    flavor: "sweet",
    rarity: "epic",
    foodOrigin: { en: "Roti Prata", zh: "印度煎餅" },
    description: {
      en: "A sky elephant that rides a giant flying prata. Each flap of its ears stretches the clouds thin.",
      zh: "踩住巨型飛餅嘅神象，耳仔一撥，連雲都拉薄。",
    },
    baseStats: { hp: 114, attack: 30, defense: 35, speed: 19 },
    skills: [
      {
        id: "sky-prata-cyclone",
        name: { en: "Sky Prata Cyclone", zh: "飛天餅旋風" },
        description: { en: "Summons a cyclone of prata discs.", zh: "召喚漫天飛餅旋風。" },
        power: 2.0,
        cooldown: 2,
      },
      {
        id: "curry-dip-flood",
        name: { en: "Curry Dip Flood", zh: "咖喱蘸海" },
        description: { en: "Floods the field with dipping curry.", zh: "傾瀉整片咖喱蘸海。" },
        power: 1.5,
        cooldown: 1,
      },
    ],
    evolvesTo: null,
    evolutionRequirement: null,
    modelUrl: "/models/prata-sky-elephant.glb",
    modelHeightM: 0.66,
    animated: true,
    rigLite: true,
    // facing-lock: 2026-08-01 player-back enemy-face
    modelYaw: Math.PI / 2,
  },

  // ── 煎蕊派（木/酸）──────────────────────────────
  {
    id: "chendol-jelly",
    seriesId: "chendol",
    stage: 1,
    name: { en: "Chendol Jelly", zh: "煎蕊仔" },
    element: "wood",
    flavor: "sour",
    rarity: "common",
    foodOrigin: { en: "Chendol", zh: "煎蕊" },
    description: {
      en: "A wiggly pandan-green jelly sprite chilling on a spoonful of shaved ice.",
      zh: "瞓喺刨冰上面嘆世界嘅斑蘭綠蕊小精靈。",
    },
    baseStats: { hp: 44, attack: 13, defense: 10, speed: 16 },
    skills: [
      {
        id: "jelly-wiggle",
        name: { en: "Jelly Wiggle", zh: "綠蕊蠕彈" },
        description: { en: "Launches wiggly green jelly.", zh: "彈出蠕蠕吓嘅綠蕊。" },
        power: 1.0,
        cooldown: 0,
      },
      {
        id: "coconut-milk-bath",
        name: { en: "Coconut Milk Bath", zh: "椰奶浴" },
        description: { en: "A creamy soak heals 20% HP.", zh: "浸個椰奶浴，回復 20% HP。" },
        power: 0,
        cooldown: 3,
        healPercent: 0.2,
      },
    ],
    evolvesTo: "chendol-warrior",
    evolutionRequirement: { items: { "pandan-jelly": 5 }, checkinCentres: 2 },
    modelUrl: "/models/chendol-jelly.glb",
    modelHeightM: 0.25,
    animated: true,
    rigLite: true,
    // facing-lock: 2026-08-01 player-back enemy-face
    modelYaw: -Math.PI / 2,
  },
  {
    id: "chendol-warrior",
    seriesId: "chendol",
    stage: 2,
    name: { en: "Chendol Warrior", zh: "煎蕊武士" },
    element: "wood",
    flavor: "sour",
    rarity: "rare",
    foodOrigin: { en: "Chendol", zh: "煎蕊" },
    description: {
      en: "A frost knight in shaved-ice armour, wielding twin whips of pandan jelly.",
      zh: "披刨冰鎧甲嘅寒霜騎士，雙手揸住斑蘭綠蕊長鞭。",
    },
    baseStats: { hp: 67, attack: 24, defense: 16, speed: 23 },
    skills: [
      {
        id: "shaved-ice-flurry",
        name: { en: "Shaved Ice Flurry", zh: "刨冰亂舞" },
        description: { en: "A flurry of ice shavings.", zh: "刨冰碎漫天亂舞。" },
        power: 1.3,
        cooldown: 1,
      },
      {
        id: "jelly-whip",
        name: { en: "Jelly Whip", zh: "綠蕊長鞭" },
        description: { en: "Lashes with springy green jelly.", zh: "用彈性綠蕊長鞭抽擊。" },
        power: 1.6,
        cooldown: 2,
      },
    ],
    evolvesTo: "chendol-snow-queen",
    evolutionRequirement: {
      items: { "pandan-jelly": 10, "shaved-ice-crystal": 1 },
      checkinCentres: 5,
    },
    modelUrl: "/models/chendol-warrior.glb",
    animated: true,
    // facing-lock: 2026-08-01 player-back enemy-face
    modelYaw: Math.PI / 2,
    modelHeightM: 0.48,
  },
  {
    id: "chendol-snow-queen",
    seriesId: "chendol",
    stage: 3,
    name: { en: "Chendol Snow Queen", zh: "煎蕊雪后" },
    element: "wood",
    flavor: "sour",
    rarity: "epic",
    foodOrigin: { en: "Chendol", zh: "煎蕊" },
    description: {
      en: "Queen of the ice mountain. Gula melaka flows down her gown like molten amber.",
      zh: "冰山之后，椰糖漿沿住雪白華服流成琥珀瀑布。",
    },
    baseStats: { hp: 102, attack: 35, defense: 26, speed: 28 },
    skills: [
      {
        id: "emerald-blizzard",
        name: { en: "Emerald Blizzard", zh: "翡翠暴雪" },
        description: { en: "A blizzard of pandan-green ice.", zh: "召喚翡翠色暴風雪。" },
        power: 2.0,
        cooldown: 2,
      },
      {
        id: "red-bean-meteor",
        name: { en: "Red Bean Meteor", zh: "紅豆流星雨" },
        description: { en: "Rains sweet red bean meteors.", zh: "召喚甜蜜紅豆流星雨。" },
        power: 1.5,
        cooldown: 1,
      },
    ],
    evolvesTo: null,
    evolutionRequirement: null,
    modelUrl: "/models/chendol-snow-queen.glb",
    modelHeightM: 0.62,
    animated: true,
    rigLite: true,
    // facing-lock: 2026-08-01 player-back enemy-face
    modelYaw: -Math.PI / 2,
  },

  // ══ 原材料層（rarity: basic）══════════════════════
  // 定位：小販美食嘅「原料」精靈——單階無進化、數值最弱、
  // 唔使入 spawnPool（spawn.ts 自動全據點可見）、出現率壓倒性。
  {
    id: "chilli-baby",
    seriesId: "chilli-baby",
    stage: 1,
    name: { en: "Chilli Baby", zh: "辣椒仔" },
    element: "fire",
    flavor: "spicy",
    rarity: "basic",
    foodOrigin: { en: "Chilli Padi", zh: "辣椒" },
    description: {
      en: "A round little chilli with a fiery temper. Bumps into foes and bursts into chilli powder.",
      zh: "圓碌碌嘅小辣椒，脾氣火爆，成日用身體撞人，撞親就爆辣椒粉。",
    },
    baseStats: { hp: 36, attack: 11, defense: 7, speed: 13 },
    skills: [
      {
        id: "fiery-temper",
        name: { en: "Fiery Temper", zh: "火爆脾氣" },
        description: {
          en: "Ignites, swells up, and rams the foe in a burst of chilli flame.",
          zh: "全身着火膨脹，向對手猛烈衝撞，爆出辣椒火焰。",
        },
        power: 1.2,
        cooldown: 2,
      },
    ],
    evolvesTo: null,
    evolutionRequirement: null,
    modelUrl: "/models/chilli-baby.glb",
    animated: true,
    rigLite: true,
    // facing-lock: 2026-08-01 player-back enemy-face
    modelYaw: -Math.PI / 2,
    modelHeightM: 0.2,
  },
  {
    id: "garlic-guard",
    seriesId: "garlic-guard",
    stage: 1,
    name: { en: "Garlic Guard", zh: "蒜頭衛兵" },
    element: "metal",
    flavor: "spicy",
    rarity: "basic",
    foodOrigin: { en: "Garlic", zh: "蒜頭" },
    description: {
      en: "A plump garlic sentry. Its pungent silver aura keeps germs — and foes — at bay.",
      zh: "肥嘟嘟嘅蒜頭哨兵，一身刺鼻銀光，病菌同敵人都唔敢埋身。",
    },
    baseStats: { hp: 40, attack: 8, defense: 12, speed: 8 },
    skills: [
      {
        id: "antibacterial-shield",
        name: { en: "Antibacterial Shield", zh: "抗菌護盾" },
        description: {
          en: "A silver garlic barrier restores 20% team HP.",
          zh: "銀色蒜香護盾包圍全隊，回復 20% HP。",
        },
        power: 0,
        cooldown: 3,
        healPercent: 0.2,
      },
    ],
    evolvesTo: null,
    evolutionRequirement: null,
    modelUrl: "/models/garlic-guard.glb",
    animated: true,
    rigLite: true,
    // facing-lock: 2026-08-01 player-back enemy-face
    modelYaw: -Math.PI / 2,
    modelHeightM: 0.2,
  },
  {
    id: "lemongrass-swordsman",
    seriesId: "lemongrass-swordsman",
    stage: 1,
    name: { en: "Lemongrass Swordsman", zh: "香茅劍客" },
    element: "wood",
    flavor: "sour",
    rarity: "basic",
    foodOrigin: { en: "Lemongrass", zh: "香茅" },
    description: {
      en: "A slender duelist who fences with a thin lemongrass blade. Every slash smells of citrus.",
      zh: "身形修長嘅劍客，手持香茅葉細劍，每一斬都帶住清新檸檬香。",
    },
    baseStats: { hp: 34, attack: 12, defense: 7, speed: 15 },
    skills: [
      {
        id: "lemongrass-sword-dance",
        name: { en: "Lemongrass Sword Dance", zh: "香茅劍舞" },
        description: {
          en: "Spins gracefully, tracing green sword arcs as leaves scatter.",
          zh: "優雅旋身劃出翠綠劍光，香茅葉隨劍舞飄落。",
        },
        power: 1.25,
        cooldown: 2,
      },
    ],
    evolvesTo: null,
    evolutionRequirement: null,
    modelUrl: "/models/lemongrass-swordsman.glb",
    animated: true,
    rigLite: true,
    // facing-lock: 2026-08-01 player-back enemy-face
    modelYaw: -Math.PI / 2,
    modelHeightM: 0.26,
  },
  {
    id: "riceball-baby",
    seriesId: "riceball-baby",
    stage: 1,
    name: { en: "Riceball Baby", zh: "飯團寶寶" },
    element: "earth",
    flavor: "sweet",
    rarity: "basic",
    foodOrigin: { en: "Rice Ball", zh: "飯團" },
    description: {
      en: "A perfectly round rice ball that attacks by rolling. Grains fly everywhere.",
      zh: "圓到完美嘅白飯團，縮成波咁碌向敵人，米粒周圍飛。",
    },
    baseStats: { hp: 42, attack: 9, defense: 11, speed: 7 },
    skills: [
      {
        id: "sticky-rice-bind",
        name: { en: "Sticky Rice Bind", zh: "糯米黏著" },
        description: {
          en: "Spits a glob of glutinous rice paste that snares the foe.",
          zh: "噴出一團糯米漿，黏住對手令佢動彈不得。",
        },
        power: 1.1,
        cooldown: 2,
      },
    ],
    evolvesTo: null,
    evolutionRequirement: null,
    modelUrl: "/models/riceball-baby.glb",
    animated: true,
    rigLite: true,
    // facing-lock: 2026-08-01 player-back enemy-face
    modelYaw: -Math.PI / 2,
    modelHeightM: 0.2,
  },
  {
    id: "vermicelli-sprite",
    seriesId: "vermicelli-sprite",
    stage: 1,
    name: { en: "Vermicelli Sprite", zh: "米粉精靈" },
    element: "water",
    flavor: "salty",
    rarity: "basic",
    foodOrigin: { en: "Rice Vermicelli", zh: "米粉" },
    description: {
      en: "A wavy sprite of silky rice noodles. Whips its soft body like a lash.",
      zh: "一束柔滑米粉化成嘅小精靈，成條身體甩起嚟好似鞭咁。",
    },
    baseStats: { hp: 36, attack: 10, defense: 8, speed: 14 },
    skills: [
      {
        id: "vermicelli-wrap",
        name: { en: "Vermicelli Wrap", zh: "米粉纏繞" },
        description: {
          en: "Extends noodle tendrils that coil around the foe in a spray of droplets.",
          zh: "伸出多條米粉觸手漩渦式纏實對手，水珠四濺。",
        },
        power: 1.15,
        cooldown: 2,
      },
    ],
    evolvesTo: null,
    evolutionRequirement: null,
    modelUrl: "/models/vermicelli-sprite.glb",
    animated: true,
    rigLite: true,
    // facing-lock: 2026-08-01 player-back enemy-face
    modelYaw: -Math.PI / 2,
    modelHeightM: 0.26,
  },
  {
    id: "egg-guard",
    seriesId: "egg-guard",
    stage: 1,
    name: { en: "Egg Guard", zh: "蛋蛋守衛" },
    element: "earth",
    flavor: "salty",
    rarity: "basic",
    foodOrigin: { en: "Egg", zh: "雞蛋" },
    description: {
      en: "A stout egg wearing its cracked shell as a helmet. Slow but dependable.",
      zh: "戴住爛蛋殼頭盔嘅硬淨蛋蛋，行得慢但係好可靠。",
    },
    baseStats: { hp: 44, attack: 7, defense: 13, speed: 6 },
    skills: [
      {
        id: "yolk-guard",
        name: { en: "Yolk Guard", zh: "蛋黃守護" },
        description: {
          en: "A warm golden yolk shield restores 20% team HP.",
          zh: "溫暖金黃蛋黃護盾守護全隊，回復 20% HP。",
        },
        power: 0,
        cooldown: 3,
        healPercent: 0.2,
      },
    ],
    evolvesTo: null,
    evolutionRequirement: null,
    modelUrl: "/models/egg-guard.glb",
    animated: true,
    // HQ remake 2026-08-02：封頂網格＋Tripo rigLite（同其他基礎）
    rigLite: true,
    // facing-lock: 2026-08-02 player-back enemy-face
    modelYaw: 0,
    modelHeightM: 0.2,
  },
  {
    id: "shrimp-hopper",
    seriesId: "shrimp-hopper",
    stage: 1,
    name: { en: "Shrimp Hopper", zh: "蝦仔跳跳" },
    element: "water",
    flavor: "sweet",
    rarity: "basic",
    foodOrigin: { en: "Fresh Shrimp", zh: "鮮蝦" },
    description: {
      en: "A springy little shrimp that ricochets off its tail. Never sits still.",
      zh: "用條尾彈嚟彈去嘅小蝦仔，一秒都坐唔定。",
    },
    baseStats: { hp: 33, attack: 11, defense: 6, speed: 16 },
    skills: [
      {
        id: "bubble-shot",
        name: { en: "Bubble Shot", zh: "水泡射擊" },
        description: {
          en: "Sprays a stream of rainbow-sheened bubbles that pop on impact.",
          zh: "連續噴出彩虹光澤水泡，命中即爆成水花。",
        },
        power: 1.15,
        cooldown: 2,
      },
    ],
    evolvesTo: null,
    evolutionRequirement: null,
    modelUrl: "/models/shrimp-hopper.glb",
    animated: true,
    rigLite: true,
    // facing-lock: 2026-08-01 player-back enemy-face
    modelYaw: -Math.PI / 2,
    modelHeightM: 0.2,
  },
  {
    id: "coconut-jelly",
    seriesId: "coconut-jelly",
    stage: 1,
    name: { en: "Coconut Jelly", zh: "椰漿啫喱" },
    element: "wood",
    flavor: "sweet",
    rarity: "basic",
    foodOrigin: { en: "Coconut Milk", zh: "椰漿" },
    description: {
      en: "A milky teardrop of coconut jelly topped with a pandan leaf. Radiates gentle warmth.",
      zh: "頭頂斑蘭葉嘅乳白椰漿啫喱，成身散發溫柔暖意。",
    },
    baseStats: { hp: 38, attack: 8, defense: 9, speed: 10 },
    skills: [
      {
        id: "coconut-heal",
        name: { en: "Coconut Heal", zh: "椰香治癒" },
        description: {
          en: "Ripples of milky light restore 20% team HP.",
          zh: "乳白光漣漪擴散全隊，回復 20% HP。",
        },
        power: 0,
        cooldown: 3,
        healPercent: 0.2,
      },
    ],
    evolvesTo: null,
    evolutionRequirement: null,
    modelUrl: "/models/coconut-jelly.glb",
    animated: true,
    rigLite: true,
    // facing-lock: 2026-08-01 player-back enemy-face
    modelYaw: -Math.PI / 2,
    modelHeightM: 0.2,
  },
  {
    id: "nasi-lemak-tot",
    seriesId: "nasi-lemak-squad",
    stage: 1,
    name: { en: "Nasi Lemak Tot", zh: "椰漿飯仔" },
    element: "earth",
    flavor: "spicy",
    rarity: "common",
    foodOrigin: { en: "Nasi Lemak", zh: "椰漿飯" },
    description: {
      en: "A tiny, fragrant lump of coconut rice wrapped snugly in a fresh banana leaf diaper. It toddles around with a single crispy anchovy on its head, spreading a gentle aroma of sweet pandan.",
      zh: "一個散發著椰香的小米飯團，裹在溫馨的芭蕉葉尿布中。它頭上戴著一條香脆的江魚仔，走起路來搖搖晃晃，散發出淡淡的斑蘭清香。",
    },
    baseStats: { hp: 45, attack: 13, defense: 10, speed: 14 },
    skills: [
      {
        id: "nasi-lemak-tot-skill-1",
        name: { en: "Pandan Whiff", zh: "斑蘭飄香" },
        description: { en: "Releases a sweet, soothing aroma of coconut and pandan that disorients opponents while dealing light damage.", zh: "釋放出香甜誘人的椰香斑蘭氣味，迷惑對手並造成輕微傷害。" },
        power: 1,
        cooldown: 0,
      },
      {
        id: "nasi-lemak-tot-skill-2",
        name: { en: "Bilis Bonk", zh: "脆炸江魚撞" },
        description: { en: "Charges forward with a crunchy, hard-hitting headbutt powered by a dried anchovy.", zh: "以爽脆堅硬的江魚仔奮力向前一撞，痛擊前方敵人。" },
        power: 1.4,
        cooldown: 2,
      },
    ],
    evolvesTo: "nasi-lemak-scout",
    evolutionRequirement: {"items":{"nasi-lemak-squad-essence":5},"checkinCentres":2},
    // 圓身飯團：rig 必敗，用靜態 Tripo mesh + 程序化 idle／攻擊
    modelUrl: "/models/nasi-lemak-tot.glb",
    modelHeightM: 0.3,
    animated: false,
    // facing-lock: 2026-08-01 player-back enemy-face
    modelYaw: -Math.PI / 2,
  },
  {
    id: "nasi-lemak-scout",
    seriesId: "nasi-lemak-squad",
    stage: 2,
    name: { en: "Nasi Lemak Scout", zh: "椰漿飯小兵" },
    element: "earth",
    flavor: "spicy",
    rarity: "rare",
    foodOrigin: { en: "Nasi Lemak", zh: "椰漿飯" },
    description: {
      en: "Outfitted for backyard adventures, this chubby rice spirit wears a hard-boiled egg slice as a protective helmet and carries a crisp cucumber shield. It is beginning to master the warm, fiery kick of sweet sambal.",
      zh: "裝備齊全的胖嘟嘟冒險小兵，戴著半顆水煮蛋做成的頭盔，手持一片清脆的小黃瓜盾牌。它已經開始學會掌控參巴辣椒醬的溫暖熱力。",
    },
    baseStats: { hp: 72, attack: 22, defense: 18, speed: 20 },
    skills: [
      {
        id: "nasi-lemak-scout-skill-1",
        name: { en: "Cucumber Shield Bash", zh: "青瓜爽脆盾" },
        description: { en: "Slams enemies with a cool, thick cucumber slice that also dampens incoming attacks.", zh: "用清涼厚實的青瓜片猛擊對手，同時抵擋迎面而來的攻勢。" },
        power: 1.1,
        cooldown: 0,
      },
      {
        id: "nasi-lemak-scout-skill-2",
        name: { en: "Sambal Splash", zh: "參巴辣醬擊" },
        description: { en: "Splashes spicy, aromatic sambal chili to inflict continuous burning damage on foes.", zh: "潑灑香辣惹味的參巴辣椒醬，對敵人造成持續的灼燒傷害。" },
        power: 1.7,
        cooldown: 2,
      },
    ],
    evolvesTo: "nasi-lemak-general",
    evolutionRequirement: {"items":{"nasi-lemak-squad-essence":10},"checkinCentres":5},
    modelUrl: "/models/nasi-lemak-scout.glb",
    modelHeightM: 0.5,
    animated: true,
    rigLite: true,
    // facing-lock: 2026-08-01 player-back enemy-face
    modelYaw: -Math.PI / 2,
  },
  {
    id: "nasi-lemak-general",
    seriesId: "nasi-lemak-squad",
    stage: 3,
    name: { en: "Nasi Lemak General", zh: "椰漿飯大將軍" },
    element: "earth",
    flavor: "spicy",
    rarity: "epic",
    foodOrigin: { en: "Nasi Lemak", zh: "椰漿飯" },
    description: {
      en: "The grand defender of the morning markets, draped in a majestic, flowing banana leaf cape. It wields a mighty golden-fried chicken wing as a sword and commands the deep, rich volcano of savory-sweet sambal.",
      zh: "晨間巴剎與熟食中心的偉大捍衛者，身披威武的芭蕉葉斗篷。它手握一隻金黃酥脆的炸雞翅神劍，能召喚出濃郁香辣的參巴火山狂潮。",
    },
    baseStats: { hp: 102, attack: 34, defense: 28, speed: 26 },
    skills: [
      {
        id: "nasi-lemak-general-skill-1",
        name: { en: "Golden Wing Slasher", zh: "酥脆炸雞斬" },
        description: { en: "Slashes through enemy lines with razor-sharp, golden-fried chicken wing blades.", zh: "揮舞利如刀刃的金黃酥脆炸雞翼，無情地橫掃敵陣。" },
        power: 1.2,
        cooldown: 0,
      },
      {
        id: "nasi-lemak-general-skill-2",
        name: { en: "Volcanic Sambal Eruption", zh: "參巴火山爆" },
        description: { en: "Unleashes a devastating geyser of fiery sambal chili that scorches the entire battlefield.", zh: "引爆火山般的烈焰參巴醬，用極致的辛辣火舌吞噬戰場。" },
        power: 2,
        cooldown: 3,
      },
    ],
    evolvesTo: null,
    evolutionRequirement: null,
    modelUrl: "/models/nasi-lemak-general.glb",
    modelHeightM: 0.65,
    animated: true,
    rigLite: true,
    // facing-lock: 2026-08-01 player-back enemy-face
    modelYaw: -Math.PI / 2,
  },
  {
    id: "otah-tot",
    seriesId: "otak-otak-clan",
    stage: 1,
    name: { en: "Otah Tot", zh: "烏達小龍" },
    element: "fire",
    flavor: "spicy",
    rarity: "common",
    foodOrigin: { en: "Otak-Otak", zh: "烏達" },
    description: {
      en: "A freshly wrapped baby spirit born from aromatic, spiced fish paste. It loves to roll around in warm charcoal ash to keep its banana-leaf wrapper toasted and fragrant.",
      zh: "誕生於芳香辛辣魚肉泥中的新鮮幼體精靈。它最愛在溫熱的炭灰中打滾，好讓身上的香蕉葉外衣保持微焦與芬芳。",
    },
    baseStats: { hp: 45, attack: 13, defense: 10, speed: 14 },
    skills: [
      {
        id: "otah-tot-skill-1",
        name: { en: "Lemongrass Smoke Puff", zh: "香茅蕉葉煙" },
        description: { en: "Releases a puff of aromatic coconut and lemongrass smoke to blind and burn the enemy.", zh: "吐出帶有椰香與香茅氣味的濃煙，燻眼並灼傷敵人。" },
        power: 1,
        cooldown: 0,
      },
      {
        id: "otah-tot-skill-2",
        name: { en: "Chili Paste Nibble", zh: "辣味魚蓉咬" },
        description: { en: "Snaps at the enemy with spicy, chili-infused fish paste that leaves a lingering sting.", zh: "用混入辣椒的魚蓉輕咬敵人，造成持續的刺痛。" },
        power: 1.4,
        cooldown: 2,
      },
    ],
    evolvesTo: "otah-swashbuckler",
    evolutionRequirement: {"items":{"otak-otak-clan-essence":5},"checkinCentres":2},
    modelUrl: "/models/otah-tot.glb",
    modelHeightM: 0.3,
    animated: true,
    // yawfix：0° 背向鏡頭；舊 +π/2 變成側身（敵人亦側）
    // facing-lock: 2026-08-01 player-back enemy-face
    modelYaw: 0,
  },
  {
    id: "otah-swashbuckler",
    seriesId: "otak-otak-clan",
    stage: 2,
    name: { en: "Otah Swashbuckler", zh: "烏達劍客" },
    element: "fire",
    flavor: "spicy",
    rarity: "rare",
    foodOrigin: { en: "Otak-Otak", zh: "烏達" },
    description: {
      en: "Steeped in rich coconut milk and wild spices, this dragon has learned the art of charcoal grilling. Its skin is perfectly toasted, releasing a mouth-watering aroma whenever it swings its claws.",
      zh: "浸潤了濃郁椰漿與野生香料，這隻龍人已掌握了炭火燒烤的奧秘。它那烤得恰到好處的皮膚在揮舞雙爪時，會散發出令人垂涎的香氣。",
    },
    baseStats: { hp: 72, attack: 22, defense: 18, speed: 20 },
    skills: [
      {
        id: "otah-swashbuckler-skill-1",
        name: { en: "Bamboo Skewer Thrust", zh: "竹籤連環刺" },
        description: { en: "Thrusts forward with sharp bamboo skewers, piercing defenses with spicy heat.", zh: "用鋒利的竹籤向前猛刺，以辛辣的熱力穿透敵方防禦。" },
        power: 1.1,
        cooldown: 0,
      },
      {
        id: "otah-swashbuckler-skill-2",
        name: { en: "Charcoal Grill Wave", zh: "炭香燒烤熱浪" },
        description: { en: "Unleashes a wave of intense heat and smoky aroma from the charcoal grill.", zh: "釋放出一股來自炭火烤爐的熾熱高溫與濃郁煙燻香氣。" },
        power: 1.7,
        cooldown: 2,
      },
    ],
    evolvesTo: "otah-pyrolord-chong",
    evolutionRequirement: {"items":{"otak-otak-clan-essence":10},"checkinCentres":5},
    modelUrl: "/models/otah-swashbuckler.glb",
    modelHeightM: 0.5,
    animated: true,
    // 同 otah-tot Meshy Hips 朝向
    // facing-lock: 2026-08-01 player-back enemy-face
    modelYaw: 0,
  },
  {
    id: "otah-pyrolord-chong",
    seriesId: "otak-otak-clan",
    stage: 3,
    name: { en: "Otah Pyrolord", zh: "烏達炎領" },
    element: "fire",
    flavor: "spicy",
    rarity: "epic",
    foodOrigin: { en: "Otak-Otak", zh: "烏達" },
    description: {
      en: "The absolute master of the grill, Otah Pyrolord Chong commands the sacred flames of the charcoal pit. It can unleash a torrent of spicy, aromatic heat that perfectly cooks anything in its path.",
      zh: "炭火烤爐的絕對主宰，烏達炎領掌控著神聖的炭坑烈焰。它能釋放出混雜著香料與高溫的熱浪，將前方的對手完美「炙烤」。",
    },
    baseStats: { hp: 102, attack: 34, defense: 28, speed: 26 },
    skills: [
      {
        id: "otah-pyrolord-chong-skill-1",
        name: { en: "Sambal Otah Torrent", zh: "烈焰參巴魚漿潮" },
        description: { en: "Deluges the battlefield in a boiling torrent of spicy, sambal-infused fish paste.", zh: "向戰場傾瀉滾燙而辛辣的參巴魚漿洪流，吞噬所有敵人。" },
        power: 1.2,
        cooldown: 0,
      },
      {
        id: "otah-pyrolord-chong-skill-2",
        name: { en: "Charcoal Ember Storm", zh: "椰殼炭火烈焰風暴" },
        description: { en: "Summons a raging storm of burning coconut-shell charcoal embers to incinerate everything.", zh: "召喚狂暴的椰殼炭火餘燼風暴，將一切燃燒殆盡。" },
        power: 2,
        cooldown: 3,
      },
    ],
    evolvesTo: null,
    evolutionRequirement: null,
    modelUrl: "/models/otah-pyrolord-chong.glb",
    modelHeightM: 0.65,
    animated: true,
    rigLite: true,
    // facing-lock: 2026-08-01 player-back enemy-face
    modelYaw: -Math.PI / 2,
  },
  {
    id: "chwee-hamlet",
    seriesId: "chwee-kueh-hamster",
    stage: 1,
    name: { en: "Chwee Hamlet", zh: "水粿鼠仔" },
    element: "earth",
    flavor: "salty",
    rarity: "common",
    foodOrigin: { en: "Chwee Kueh", zh: "水粿" },
    description: {
      en: "A chubby little hamster spirit that lives in bamboo steamers. It has a soft, bouncy white body made of steamed rice flour and loves to nestle in warm, savory chai poh.",
      zh: "一隻圓滾滾的倉鼠精靈，生活在竹蒸籠裡。牠擁有蒸米粉製成的柔軟彈性白色身體，最喜歡窩在溫熱香鹹的菜脯裡。",
    },
    baseStats: { hp: 45, attack: 13, defense: 10, speed: 14 },
    skills: [
      {
        id: "chwee-hamlet-skill-1",
        name: { en: "Cup-Mold Steamer Leap", zh: "砵仔蒸騰躍" },
        description: { en: "Bounces forcefully out of its metal cup mold, crushing enemies beneath its heavy rice-cake body.", zh: "從金屬蒸杯中強力彈起，以厚實的水粿糕體重壓對手。" },
        power: 1,
        cooldown: 0,
      },
      {
        id: "chwee-hamlet-skill-2",
        name: { en: "Savory Chai Poh Splatter", zh: "鹹香菜脯潑" },
        description: { en: "Flings a scatter of glistening, salty preserved radish to blind and sting enemies.", zh: "甩出一手油亮鹹香的碎菜脯，以濃郁的鹹氣刺痛並干擾敵方視線。" },
        power: 1.4,
        cooldown: 2,
      },
    ],
    evolvesTo: "chwee-sentry",
    evolutionRequirement: {"items":{"chwee-kueh-hamster-essence":5},"checkinCentres":2},
    modelUrl: "/models/chwee-hamlet.glb",
    modelHeightM: 0.3,
    animated: true,
    rigLite: true,
    // facing-lock: 2026-08-01 player-back enemy-face
    modelYaw: -Math.PI / 2,
  },
  {
    id: "chwee-sentry",
    seriesId: "chwee-kueh-hamster",
    stage: 2,
    name: { en: "Chwee Sentry", zh: "水粿精兵" },
    element: "earth",
    flavor: "salty",
    rarity: "rare",
    foodOrigin: { en: "Chwee Kueh", zh: "水粿" },
    description: {
      en: "With a body hardened by perfect steaming, this bipedal hamster warrior proudly guards the hawker stall. It wears armor made of glazed ceramic saucers and carries a wooden paddle slick with chili oil.",
      zh: "經過完美蒸製淬鍊的雙足倉鼠戰士，自豪地守護著小販攤位。牠身穿釉面陶碗製成的鎧甲，手持沾滿辣椒油的木鏟。",
    },
    baseStats: { hp: 72, attack: 22, defense: 18, speed: 20 },
    skills: [
      {
        id: "chwee-sentry-skill-1",
        name: { en: "Chai Poh Bastion Bash", zh: "菜脯重盾擊" },
        description: { en: "Summons a solid wall of compressed preserved radish to block attacks before shattering it forward as shrapnel.", zh: "召喚由緊實菜脯築成的堅固重盾，阻擋攻擊後將其震碎為飛石碎片痛擊前方。" },
        power: 1.1,
        cooldown: 0,
      },
      {
        id: "chwee-sentry-skill-2",
        name: { en: "Bamboo Spatula Sweep", zh: "竹製糕鏟掃" },
        description: { en: "Sweeps a giant flat bamboo spatula across the ground, tripping foes and launching them into the air.", zh: "揮舞巨型竹製水粿鏟橫掃地面，絆倒對手並將其鏟飛至半空。" },
        power: 1.7,
        cooldown: 2,
      },
    ],
    evolvesTo: "chwee-shogun",
    evolutionRequirement: {"items":{"chwee-kueh-hamster-essence":10},"checkinCentres":5},
    modelUrl: "/models/chwee-sentry.glb",
    modelHeightM: 0.5,
    animated: true,
    // facing-lock: 2026-08-01 player-back enemy-face
    modelYaw: Math.PI / 2,
  },
  {
    id: "chwee-shogun",
    seriesId: "chwee-kueh-hamster",
    stage: 3,
    name: { en: "Chwee Shogun", zh: "水粿大將" },
    element: "earth",
    flavor: "salty",
    rarity: "epic",
    foodOrigin: { en: "Chwee Kueh", zh: "水粿" },
    description: {
      en: "The ultimate guardian of the savory breakfast. This grand hamster shogun commands the earthen steam, clad in interlocking ceramic-plate armor dripping with sweet-savory chili oil and topped with an elite mound of fragrant caramelized radish.",
      zh: "美味早餐的終極守護者。這位雄偉的倉鼠大將掌控著大地的蒸氣，身披由多層陶碟連綴而成的重甲，甲冑上流淌著甜辣的紅油，並覆蓋著芬芳四溢的焦糖色炒菜脯。",
    },
    baseStats: { hp: 102, attack: 34, defense: 28, speed: 26 },
    skills: [
      {
        id: "chwee-shogun-skill-1",
        name: { en: "Grand Steamer Pressure Eruption", zh: "巨神蒸籠大爆發" },
        description: { en: "Unleashes a massive burst of scalding rice-scented steam from giant bamboo steamers to burn all opponents.", zh: "瞬間掀開巨型竹蒸籠，釋放高壓灼熱的米香蒸氣灼傷全體敵方。" },
        power: 1.2,
        cooldown: 0,
      },
      {
        id: "chwee-shogun-skill-2",
        name: { en: "Caramelized Chai Poh Tempest", zh: "焦香菜脯狂風暴" },
        description: { en: "Conjures a raging whirlwind of dark, sweet-and-salty caramelized radish that pummels the battlefield.", zh: "召喚狂暴的深色焦香醬油菜脯風暴，以排山倒海之勢無情痛擊整個戰場。" },
        power: 2,
        cooldown: 3,
      },
    ],
    evolvesTo: null,
    evolutionRequirement: null,
    modelUrl: "/models/chwee-shogun.glb",
    modelHeightM: 0.65,
    animated: true,
    // facing-lock: 2026-08-01 player-back enemy-face
    modelYaw: Math.PI / 2,
  },
  {
    id: "kachang-snowling",
    seriesId: "ice-kachang-christmas-dragon",
    stage: 1,
    name: { en: "Kachang Snowling", zh: "冰豆龍仔" },
    element: "water",
    flavor: "sweet",
    rarity: "common",
    foodOrigin: { en: "Ice Kachang", zh: "紅豆冰" },
    description: {
      en: "A chubby baby dragon made of fluffy shaved ice draped in vibrant red rose syrup and green jelly glaze. It sports a cute holly-berry scarf and holds a festive striped peppermint ice spoon.",
      zh: "隻身圓滾滾的幼龍，全身由綿密刨冰砌成，淋上鮮紅玫瑰糖漿與翠綠仙草醬。戴著冬青漿果圍巾，手握一支聖誕糖果棒造型的甜品匙。",
    },
    baseStats: { hp: 45, attack: 13, defense: 10, speed: 14 },
    skills: [
      {
        id: "kachang-snowling-skill-1",
        name: { en: "Sugar Snow Flurry", zh: "甜糖細雪風暴" },
        description: { en: "Summons a chilling shower of finely shaved ice drenched in sweet syrup to pelt enemies.", zh: "召喚淋滿甜糖漿的細碎刨雪，猛烈轟炸敵方陣營。" },
        power: 1,
        cooldown: 0,
      },
      {
        id: "kachang-snowling-skill-2",
        name: { en: "Minty Scoop Slam", zh: "薄荷冰球重擊" },
        description: { en: "Slams a giant frozen scoop of mint-infused ice down onto a target, chilling them to the bone.", zh: "投擲巨大的冰涼薄荷雪糕球砸向目標，造成極致冰霜衝擊。" },
        power: 1.4,
        cooldown: 2,
      },
    ],
    evolvesTo: "kachang-frost-drake",
    evolutionRequirement: {"items":{"ice-kachang-christmas-dragon-essence":5},"checkinCentres":2},
    modelUrl: "/models/kachang-snowling.glb",
    modelHeightM: 0.3,
    animated: true,
    // facing-lock: 2026-07-29 player-back enemy-face
    modelYaw: 0,
  },
  {
    id: "kachang-frost-drake",
    seriesId: "ice-kachang-christmas-dragon",
    stage: 2,
    name: { en: "Kachang Frost Drake", zh: "紅豆雪山龍" },
    element: "water",
    flavor: "sweet",
    rarity: "rare",
    foodOrigin: { en: "Ice Kachang", zh: "紅豆冰" },
    description: {
      en: "A proud reptilian warrior whose dragon scale armor glistens like sweet corn kernels and caramelized gula melaka. It wields an ice-scraper halberd dripping with chilled rose syrup and wears a wreath of glowing Christmas pine needles.",
      zh: "英姿颯爽的龍族武士，胸甲如玉米粒般金黃耀眼，搭配焦糖色椰糖龍鱗。手持滴著玫瑰冷漿的雙刃刨冰戟，頸間環繞著發光的聖誕松針環。",
    },
    baseStats: { hp: 72, attack: 22, defense: 18, speed: 20 },
    skills: [
      {
        id: "kachang-frost-drake-skill-1",
        name: { en: "Rose Syrup Torrent", zh: "玫瑰糖漿怒濤" },
        description: { en: "Unleashes a surging wave of sweet rose syrup that washes over the battlefield and freezes enemies.", zh: "噴湧出濃郁冰涼的玫瑰糖漿巨浪，吞噬並凍結敵方。" },
        power: 1.1,
        cooldown: 0,
      },
      {
        id: "kachang-frost-drake-skill-2",
        name: { en: "Razor Scraper Strike", zh: "刨冰飛刃斬" },
        description: { en: "Slashes with razor-sharp ice shavings to strike all foes in its path.", zh: "如刨冰機般甩出銳利冰刃，切碎沿途所有敵人。" },
        power: 1.7,
        cooldown: 2,
      },
    ],
    evolvesTo: "kachang-deity-sovereign",
    evolutionRequirement: {"items":{"ice-kachang-christmas-dragon-essence":10},"checkinCentres":5},
    modelUrl: "/models/kachang-frost-drake.glb",
    modelHeightM: 0.5,
    animated: true,
    // facing-lock: 2026-07-29 player-back enemy-face
    modelYaw: 0,
  },
  {
    id: "kachang-deity-sovereign",
    seriesId: "ice-kachang-christmas-dragon",
    stage: 3,
    name: { en: "Kachang Feast Guardian", zh: "彩冰聖誕神" },
    element: "water",
    flavor: "sweet",
    rarity: "epic",
    foodOrigin: { en: "Ice Kachang", zh: "紅豆冰" },
    description: {
      en: "A magnificent six-armed guardian deity reborn in full Christmas grandeur. A glowing golden-star mandala aura shines behind its head while its six arms grip sacred food-forged implements to spread festive cheer.",
      zh: "幻化為六臂聖誕護法神祗，頭後懸浮著璀璨的八角星聖誕冰晶光輪。六隻手臂各持由美食化成的法器，散發濃郁甜蜜的聖誕節慶神光。",
    },
    baseStats: { hp: 102, attack: 34, defense: 28, speed: 26 },
    skills: [
      {
        id: "kachang-deity-sovereign-skill-1",
        name: { en: "Sweet Ice Mandala", zh: "七寶冰雪曼陀羅" },
        description: { en: "Radiates a majestic aura of iced syrups and attap seeds that crushes opponents with frozen power.", zh: "降下凝聚七彩糖漿與亞答籽靈氣的冰雪聖光，強勢壓制敵方。" },
        power: 1.2,
        cooldown: 0,
      },
      {
        id: "kachang-deity-sovereign-skill-2",
        name: { en: "Six-Armed Mountain Avalanche", zh: "六臂冰山雪崩衝" },
        description: { en: "Strikes relentlessly with six ice-clad arms, hurling a colossal avalanche of shaved ice and toppings onto the enemy team.", zh: "揮動六臂召喚傾盆冰山與巨量配料雪崩，以無比威勢碾壓全場對手。" },
        power: 2,
        cooldown: 3,
      },
    ],
    evolvesTo: null,
    evolutionRequirement: null,
    modelUrl: "/models/kachang-deity-sovereign.glb",
    modelHeightM: 0.65,
    animated: true,
    // facing-lock: 2026-07-29 player-back enemy-face
    modelYaw: 0,
  },
  {
    id: "wanton-pup",
    seriesId: "wanton-mee",
    stage: 1,
    name: { en: "Wanton Pup", zh: "雲吞仔" },
    element: "metal",
    flavor: "salty",
    rarity: "common",
    foodOrigin: { en: "Wanton Mee", zh: "雲吞麵" },
    description: {
      en: "Stage 1 of the Wanton Mee line. (guided)",
      zh: "雲吞麵系列第 1 階。（依指示調整）",
    },
    baseStats: { hp: 45, attack: 13, defense: 10, speed: 14 },
    skills: [
      {
        id: "wanton-pup-skill-1",
        name: { en: "Plump Wanton Bomb", zh: "炸雲吞飛彈" },
        description: { en: "Hurls a piping-hot wanton to deal salty metal-element damage to a single foe.", zh: "投擲熱騰騰的金黃雲吞，對單體敵人造成鹹香的金屬傷害。" },
        power: 1,
        cooldown: 0,
      },
      {
        id: "wanton-pup-skill-2",
        name: { en: "Springy Noodle Whip", zh: "竹升麵彈鞭" },
        description: { en: "Lashes target enemies with flexible, springy egg noodles.", zh: "揮舞爽口彈牙的竹升麵，鞭打前方的敵人。" },
        power: 1.4,
        cooldown: 2,
      },
    ],
    evolvesTo: "charsiu-blade",
    evolutionRequirement: {"items":{"wanton-mee-essence":5},"checkinCentres":2},
    modelUrl: "/models/wanton-pup.glb",
    modelHeightM: 0.3,
    // facing-lock: 2026-07-29 player-back enemy-face
    modelYaw: 0,
  },
  {
    id: "charsiu-blade",
    seriesId: "wanton-mee",
    stage: 2,
    name: { en: "Char Siu Blade", zh: "叉燒刀客" },
    element: "metal",
    flavor: "salty",
    rarity: "rare",
    foodOrigin: { en: "Wanton Mee", zh: "雲吞麵" },
    description: {
      en: "Stage 2 of the Wanton Mee line. (guided)",
      zh: "雲吞麵系列第 2 階。（依指示調整）",
    },
    baseStats: { hp: 72, attack: 22, defense: 18, speed: 20 },
    skills: [
      {
        id: "charsiu-blade-skill-1",
        name: { en: "Honey-Glazed Cleave", zh: "蜜汁叉燒斬" },
        description: { en: "Slashes an enemy with a caramelized blade to rend their armor.", zh: "揮舞焦香蜜汁叉燒刃，斬斷對手的防禦。" },
        power: 1.1,
        cooldown: 0,
      },
      {
        id: "charsiu-blade-skill-2",
        name: { en: "Dark Vinegar Silence", zh: "黑醋封喉刺" },
        description: { en: "Splashes pungent dark vinegar onto the target, dealing damage and suppressing their skills.", zh: "潑灑濃郁酸香的黑醋，造成傷害並封印敵人的技能。" },
        power: 1.7,
        cooldown: 2,
      },
    ],
    evolvesTo: "wanton-mee-shogun",
    evolutionRequirement: {"items":{"wanton-mee-essence":10},"checkinCentres":5},
    modelUrl: "/models/charsiu-blade.glb",
    modelHeightM: 0.5,
    // facing-lock: 2026-07-29 player-back enemy-face
    modelYaw: 0,
  },
  {
    id: "wanton-mee-shogun",
    seriesId: "wanton-mee",
    stage: 3,
    name: { en: "Wanton Mee Shogun", zh: "雲吞麵將軍" },
    element: "metal",
    flavor: "salty",
    rarity: "epic",
    foodOrigin: { en: "Wanton Mee", zh: "雲吞麵" },
    description: {
      en: "Stage 3 of the Wanton Mee line. (guided)",
      zh: "雲吞麵系列第 3 階。（依指示調整）",
    },
    baseStats: { hp: 102, attack: 34, defense: 28, speed: 26 },
    skills: [
      {
        id: "wanton-mee-shogun-skill-1",
        name: { en: "Thousand Strand Slash", zh: "千麵萬縷斬" },
        description: { en: "Unleashes a whirlwind of razor-sharp noodle blades that shreds all foes.", zh: "揮斬出如鋼絲般鋒利的千縷麵條，撕裂全體敵人。" },
        power: 1.2,
        cooldown: 0,
      },
      {
        id: "wanton-mee-shogun-skill-2",
        name: { en: "Caramelized Barricade", zh: "蜜汁叉燒鐵壁" },
        description: { en: "Summons a thick layer of glazed char siu armor that retaliates against striking attackers.", zh: "凝聚厚重的焦香叉燒鎧甲，並向攻擊者反彈傷害。" },
        power: 2,
        cooldown: 3,
      },
    ],
    evolvesTo: null,
    evolutionRequirement: null,
    modelUrl: "/models/wanton-mee-shogun.glb",
    modelHeightM: 0.65,
    // facing-lock: 2026-07-29 player-back enemy-face
    modelYaw: 0,
  },
];

export const SPECIES_MAP: Record<string, Species> = Object.fromEntries(
  SPECIES.map((s) => [s.id, s])
);

export const SERIES_MAP: Record<string, SpeciesSeries> = Object.fromEntries(
  SERIES.map((s) => [s.id, s])
);

/** 未來精靈備份表（概念圖出現但未入 MVP 名單）：沙嗲仙子、咖哩獅、雲吞妖、燒肉魔、蠔煎鬼、沙嗲串兵、金鳳炒粿仙、飛餅神象、辣椒螃蟹王 */
