import type { Rarity, Species, SpeciesSeries } from "./types";

/**
 * 圖鑑門類（順序 = 顯示順序）：由 rarity 推導，唔使逐隻精靈加欄位。
 * 將來加聖獸／SSS 級：新增 rarity 值＋喺呢度加一條配置＋i18n `dex.category{Id}` 標籤即可。
 */
export const DEX_CATEGORIES: { id: string; rarities: readonly Rarity[] }[] = [
  { id: "standard", rarities: ["common", "rare", "epic", "legendary"] },
  { id: "basic", rarities: ["basic"] },
];

export const SERIES: SpeciesSeries[] = [
  {
    id: "laksa",
    name: { en: "Noodle Clan", zh: "麵食家族" },
    element: "fire",
    flavor: "spicy",
    foodOrigin: { en: "Laksa", zh: "叻沙" },
  },
  {
    id: "bak-kut-teh",
    name: { en: "Bak Kut Teh Order", zh: "肉骨茶系" },
    element: "metal",
    flavor: "bitter",
    foodOrigin: { en: "Bak Kut Teh", zh: "肉骨茶" },
  },
  {
    id: "satay",
    name: { en: "Satay Legion", zh: "沙嗲軍團" },
    element: "fire",
    flavor: "spicy",
    foodOrigin: { en: "Satay", zh: "沙嗲" },
  },
  {
    id: "chilli-baby",
    name: { en: "Chilli Baby", zh: "辣椒仔" },
    element: "fire",
    flavor: "spicy",
    foodOrigin: { en: "Chilli Padi", zh: "辣椒" },
  },
  {
    id: "garlic-guard",
    name: { en: "Garlic Guard", zh: "蒜頭衛兵" },
    element: "metal",
    flavor: "spicy",
    foodOrigin: { en: "Garlic", zh: "蒜頭" },
  },
  {
    id: "lemongrass-swordsman",
    name: { en: "Lemongrass Swordsman", zh: "香茅劍客" },
    element: "wood",
    flavor: "sour",
    foodOrigin: { en: "Lemongrass", zh: "香茅" },
  },
  {
    id: "vermicelli-sprite",
    name: { en: "Vermicelli Sprite", zh: "米粉精靈" },
    element: "water",
    flavor: "salty",
    foodOrigin: { en: "Rice Vermicelli", zh: "米粉" },
  },
  {
    id: "egg-guard",
    name: { en: "Egg Guard", zh: "蛋蛋守衛" },
    element: "earth",
    flavor: "salty",
    foodOrigin: { en: "Egg", zh: "雞蛋" },
  },
  {
    id: "shrimp-hopper",
    name: { en: "Shrimp Hopper", zh: "蝦仔跳跳" },
    element: "water",
    flavor: "sweet",
    foodOrigin: { en: "Fresh Shrimp", zh: "鮮蝦" },
  },
  {
    id: "nasi-lemak-squad",
    name: { en: "Nasi Lemak Squad", zh: "椰漿飯小隊" },
    element: "earth",
    flavor: "spicy",
    foodOrigin: { en: "Nasi Lemak", zh: "椰漿飯" },
  },
];

export const SPECIES: Species[] = [
  {
    id: "little-laksa",
    seriesId: "laksa",
    stage: 1,
    name: { en: "Little Laksa", zh: "叻沙仔" },
    element: "fire",
    flavor: "spicy",
    rarity: "common",
    foodOrigin: { en: "Laksa", zh: "叻沙" },
    description: {
      en: "A tiny shrimp spirit wearing a laksa leaf hat. Mildly spicy when startled.",
      zh: "戴住叻沙葉帽嘅小蝦精，嚇親會微微辣。",
    },
    baseStats: { hp: 42, attack: 15, defense: 8, speed: 16 },
    skills: [
      {
        id: "broth-splash",
        name: { en: "Broth Splash", zh: "湯底潑濺" },
        description: { en: "Splashes hot laksa broth.", zh: "潑灑滾燙叻沙湯。" },
        power: 1.0,
        cooldown: 0,
      },
      {
        id: "coconut-shield",
        name: { en: "Coconut Shield", zh: "椰漿護盾" },
        description: { en: "Thick coconut milk softens blows.", zh: "濃椰漿卸走攻擊。" },
        power: 0,
        cooldown: 3,
        healPercent: 0.2,
      },
    ],
    evolvesTo: "laksa-warrior",
    evolutionRequirement: { items: { "shrimp-shell-shard": 5 }, checkinCentres: 2 },
    modelUrl: "/models/little-laksa.glb",
    animUrls: { idle: "/models/little-laksa-walk.glb", walk: "/models/little-laksa-walk.glb", hit: "/models/little-laksa-walk.glb" },
    modelHeightM: 0.3,
    animated: true,
    // verify5：+π/2 仍背敵；改 -π/2
    // facing-lock: 2026-08-01 player-back enemy-face
    modelYaw: -Math.PI / 2,
  },
  {
    id: "laksa-warrior",
    seriesId: "laksa",
    stage: 2,
    name: { en: "Laksa Warrior", zh: "叻沙武士" },
    element: "fire",
    flavor: "spicy",
    rarity: "rare",
    foodOrigin: { en: "Laksa", zh: "叻沙" },
    description: {
      en: "Armoured in shrimp shell plate, cloaked in a laksa leaf. Its claws simmer with spice.",
      zh: "披蝦殼鎧甲、戴叻沙葉披風，一雙蝦鉗辣力沸騰。",
    },
    baseStats: { hp: 68, attack: 26, defense: 16, speed: 22 },
    skills: [
      {
        id: "shell-claw",
        name: { en: "Shell Claw", zh: "蝦殼鉗擊" },
        description: { en: "Crushes with armoured claws.", zh: "用裝甲蝦鉗夾擊。" },
        power: 1.3,
        cooldown: 1,
      },
      {
        id: "spicy-surge",
        name: { en: "Spicy Surge", zh: "辣浪翻騰" },
        description: { en: "A wave of chilli-laden broth.", zh: "掀起辣椒湯浪。" },
        power: 1.6,
        cooldown: 2,
      },
    ],
    evolvesTo: "laksa-dragon",
    evolutionRequirement: {
      items: { "shrimp-shell-shard": 10, "laksa-soul": 1 },
      checkinCentres: 5,
    },
    modelUrl: "/models/laksa-warrior.glb",
    animUrls: { idle: "/models/laksa-warrior-idle.glb", walk: "/models/laksa-warrior-walk.glb" },
    modelHeightM: 0.5,
    animated: true,
    // yaw sweep：0 背向鏡頭對敵；舊 -π/2 側身
    // facing-lock: 2026-08-01 player-back enemy-face
    modelYaw: 0,
  },
  {
    id: "laksa-dragon",
    seriesId: "laksa",
    stage: 3,
    name: { en: "Laksa Dragon", zh: "叻沙龍" },
    element: "fire",
    flavor: "spicy",
    rarity: "legendary",
    foodOrigin: { en: "Laksa", zh: "叻沙" },
    description: {
      en: "A dragon forged in boiling laksa broth. Its tail flame never goes out.",
      zh: "喺沸騰叻沙湯中誕生嘅神龍，尾焰永不熄滅。",
    },
    baseStats: { hp: 105, attack: 40, defense: 24, speed: 30 },
    skills: [
      {
        id: "spice-inferno",
        name: { en: "Spice Inferno", zh: "香料烈焰" },
        description: { en: "Breathes a torrent of burning spice.", zh: "噴出灼熱香料烈焰。" },
        power: 2.2,
        cooldown: 2,
      },
      {
        id: "dragon-noodle-whip",
        name: { en: "Dragon Noodle Whip", zh: "龍鬚麵鞭" },
        description: { en: "Lashes with thick vermicelli.", zh: "用粗米粉長鞭抽擊。" },
        power: 1.5,
        cooldown: 1,
      },
    ],
    evolvesTo: null,
    evolutionRequirement: null,
    modelUrl: "/models/laksa-dragon.glb",
    animUrls: { idle: "/models/laksa-dragon-idle.glb", walk: "/models/laksa-dragon-walk.glb" },
    modelHeightM: 0.65,
    animated: true,
    // yaw sweep：0 背向鏡頭；舊 -π/2 側身扭頸
    // facing-lock: 2026-08-01 player-back enemy-face
    modelYaw: 0,
  },
  {
    id: "bkt-cub",
    seriesId: "bak-kut-teh",
    stage: 1,
    name: { en: "Bak Kut Cub", zh: "肉骨仔" },
    element: "metal",
    flavor: "bitter",
    rarity: "common",
    foodOrigin: { en: "Bak Kut Teh", zh: "肉骨茶" },
    description: {
      en: "A panda cub wearing a pork-rib helmet, raised on peppery herbal soup.",
      zh: "戴住排骨頭盔嘅熊貓仔，飲胡椒藥膳湯大。",
    },
    baseStats: { hp: 50, attack: 11, defense: 14, speed: 10 },
    skills: [
      {
        id: "rib-bonk",
        name: { en: "Rib Bonk", zh: "排骨敲擊" },
        description: { en: "Bonks with a pork rib.", zh: "用排骨敲落去。" },
        power: 1.0,
        cooldown: 0,
      },
      {
        id: "herbal-sip",
        name: { en: "Herbal Sip", zh: "藥膳補湯" },
        description: { en: "Sips soup to restore 25% HP.", zh: "飲啖湯回復 25% HP。" },
        power: 0,
        cooldown: 3,
        healPercent: 0.25,
      },
    ],
    evolvesTo: "bkt-warrior",
    evolutionRequirement: { items: { "spice-essence": 5 }, checkinCentres: 2 },
    modelUrl: "/models/bkt-cub.glb",
    animUrls: { idle: "/models/bkt-cub-idle.glb", walk: "/models/bkt-cub-walk.glb" },
    modelHeightM: 0.35,
    animated: true,
    rigLite: true,
    // facing-lock: 2026-08-01 player-back enemy-face
    modelYaw: -Math.PI / 2,
  },
  {
    id: "bkt-warrior",
    seriesId: "bak-kut-teh",
    stage: 2,
    name: { en: "Bak Kut Warrior", zh: "骨茶武士" },
    element: "metal",
    flavor: "bitter",
    rarity: "rare",
    foodOrigin: { en: "Bak Kut Teh", zh: "肉骨茶" },
    description: {
      en: "A samurai panda in rib-bone armour, wielding a youtiao club and bowl shield.",
      zh: "披骨甲嘅熊貓武士，手持油條棍同湯碗盾。",
    },
    baseStats: { hp: 78, attack: 20, defense: 24, speed: 14 },
    skills: [
      {
        id: "youtiao-strike",
        name: { en: "Youtiao Strike", zh: "油條重擊" },
        description: { en: "Swings a crispy youtiao club.", zh: "揮動香脆油條棍。" },
        power: 1.3,
        cooldown: 1,
      },
      {
        id: "pepper-guard",
        name: { en: "Pepper Guard", zh: "胡椒鐵壁" },
        description: { en: "Peppery aura raises defense.", zh: "胡椒氣場提升防禦。" },
        power: 0.8,
        cooldown: 2,
      },
    ],
    evolvesTo: "bkt-grandmaster",
    evolutionRequirement: { items: { "spice-essence": 10 }, checkinCentres: 5 },
    modelUrl: "/models/bkt-warrior.glb",
    animUrls: { idle: "/models/bkt-warrior-idle.glb", walk: "/models/bkt-warrior-walk.glb", attack: "/models/bkt-warrior-attack.glb" },
    modelHeightM: 0.5,
    animated: true,
    // facing-lock: 2026-08-01 player-back enemy-face
    modelYaw: Math.PI / 2,
  },
  {
    id: "bkt-grandmaster",
    seriesId: "bak-kut-teh",
    stage: 3,
    name: { en: "Bak Kut Grandmaster", zh: "骨茶宗師" },
    element: "metal",
    flavor: "bitter",
    rarity: "epic",
    foodOrigin: { en: "Bak Kut Teh", zh: "肉骨茶" },
    description: {
      en: "In golden herb-forged armour, the grandmaster guards every claypot in the land.",
      zh: "身穿藥膳金甲嘅宗師，守護全島每一煲肉骨茶。",
    },
    baseStats: { hp: 115, attack: 30, defense: 36, speed: 18 },
    skills: [
      {
        id: "garlic-meteor",
        name: { en: "Garlic Meteor", zh: "蒜頭流星" },
        description: { en: "Rains whole garlic cloves.", zh: "召喚蒜頭流星雨。" },
        power: 1.9,
        cooldown: 2,
      },
      {
        id: "claypot-slam",
        name: { en: "Claypot Slam", zh: "砂鍋猛擊" },
        description: { en: "Slams down a scalding claypot.", zh: "用滾燙砂鍋猛砸。" },
        power: 1.6,
        cooldown: 1,
      },
    ],
    evolvesTo: null,
    evolutionRequirement: null,
    modelUrl: "/models/bkt-grandmaster.glb",
    animUrls: { idle: "/models/bkt-grandmaster-idle.glb", walk: "/models/bkt-grandmaster-walk.glb" },
    // facing-lock: 2026-08-01 player-back enemy-face
    modelYaw: 0,
    modelHeightM: 0.65,
    animated: true,
  },
  {
    id: "satay-skewerling",
    seriesId: "satay",
    stage: 1,
    name: { en: "Satay Skewerling", zh: "沙嗲仔" },
    element: "fire",
    flavor: "spicy",
    rarity: "common",
    foodOrigin: { en: "Satay", zh: "沙嗲" },
    description: {
      en: "A tiny skewer soldier marinated in turmeric. Dreams of the great charcoal fire.",
      zh: "醃透黃薑嘅串燒小兵，日日夢想住上炭爐。",
    },
    baseStats: { hp: 43, attack: 15, defense: 9, speed: 16 },
    skills: [
      {
        id: "skewer-jab",
        name: { en: "Skewer Jab", zh: "竹籤突刺" },
        description: { en: "Jabs with a bamboo skewer.", zh: "用竹籤快速突刺。" },
        power: 1.0,
        cooldown: 0,
      },
      {
        id: "ketupat-rest",
        name: { en: "Ketupat Rest", zh: "馬來米糕休整" },
        description: { en: "Snacks on ketupat to heal 20% HP.", zh: "食啖馬來米糕，回復 20% HP。" },
        power: 0,
        cooldown: 3,
        healPercent: 0.2,
      },
    ],
    evolvesTo: "satay-warrior",
    evolutionRequirement: { items: { "bamboo-skewer": 5 }, checkinCentres: 2 },
    modelUrl: "/models/satay-skewerling.glb",
    animUrls: { idle: "/models/satay-skewerling-idle.glb", walk: "/models/satay-skewerling-walk.glb" },
    modelHeightM: 0.3,
    animated: true,
    rigLite: true,
    // facing-lock: 2026-08-01 player-back enemy-face
    modelYaw: -Math.PI / 2,
  },
  {
    id: "satay-warrior",
    seriesId: "satay",
    stage: 2,
    name: { en: "Satay Warrior", zh: "沙嗲武士" },
    element: "fire",
    flavor: "spicy",
    rarity: "rare",
    foodOrigin: { en: "Satay", zh: "沙嗲" },
    description: {
      en: "A grill-hardened lancer cloaked in peanut sauce, wielding three skewers at once.",
      zh: "炭火煉成嘅長槍手，披花生醬戰袍，一手揸三串。",
    },
    baseStats: { hp: 67, attack: 26, defense: 15, speed: 23 },
    skills: [
      {
        id: "charcoal-grill",
        name: { en: "Charcoal Grill", zh: "炭火串燒" },
        description: { en: "Breathes searing charcoal heat.", zh: "噴出炙熱炭火氣浪。" },
        power: 1.3,
        cooldown: 1,
      },
      {
        id: "triple-skewer",
        name: { en: "Triple Skewer", zh: "三串連擊" },
        description: { en: "Strikes thrice with skewers.", zh: "三串齊發連環刺擊。" },
        power: 1.6,
        cooldown: 2,
      },
    ],
    evolvesTo: "satay-flame-emperor",
    evolutionRequirement: {
      items: { "bamboo-skewer": 10, "charcoal-ember": 1 },
      checkinCentres: 5,
    },
    modelUrl: "/models/satay-warrior.glb",
    animUrls: { idle: "/models/satay-warrior-idle.glb", walk: "/models/satay-warrior-walk.glb" },

    // HQ remake 2026-08-02：Tripo→Meshy fullRig（modelYaw 待 facing-lock）
    // facing-lock: 2026-08-02 player-back enemy-face

    modelYaw: 0,
    modelHeightM: 0.5,
    animated: true,

  },
  {
    id: "satay-flame-emperor",
    seriesId: "satay",
    stage: 3,
    name: { en: "Satay Flame Emperor", zh: "沙嗲炎帝" },
    element: "fire",
    flavor: "spicy",
    rarity: "epic",
    foodOrigin: { en: "Satay", zh: "沙嗲" },
    description: {
      en: "Emperor of the open flame. One fan of its wing and a hundred skewers ignite.",
      zh: "明火之帝，翼一撥，百串齊燃。",
    },
    baseStats: { hp: 100, attack: 39, defense: 23, speed: 30 },
    skills: [
      {
        id: "hundred-skewer-storm",
        name: { en: "Hundred Skewer Storm", zh: "百串燎原" },
        description: { en: "Rains a hundred flaming skewers.", zh: "百枝火串漫天落下。" },
        power: 2.1,
        cooldown: 2,
      },
      {
        id: "peanut-sauce-flood",
        name: { en: "Peanut Sauce Flood", zh: "花生醬洪流" },
        description: { en: "Unleashes a torrent of peanut sauce.", zh: "傾瀉香濃花生醬洪流。" },
        power: 1.5,
        cooldown: 1,
      },
    ],
    evolvesTo: null,
    evolutionRequirement: null,
    modelUrl: "/models/satay-flame-emperor.glb",
    animUrls: { idle: "/models/satay-flame-emperor-idle.glb", walk: "/models/satay-flame-emperor-walk.glb" },
    modelHeightM: 0.65,
    animated: true,
    // yaw sweep 968a49：-90 面向對手；+90 背敵；0 側身含糊
    // facing-lock: 2026-08-01 player-back enemy-face
    modelYaw: -Math.PI / 2,
  },
  {
    id: "chilli-baby",
    seriesId: "chilli-baby",
    stage: 1,
    name: { en: "Chilli Baby", zh: "辣椒仔" },
    element: "fire",
    flavor: "spicy",
    rarity: "basic",
    foodOrigin: { en: "Chilli Padi", zh: "辣椒" },
    description: {
      en: "A round little chilli with a fiery temper. Bumps into foes and bursts into chilli powder.",
      zh: "圓碌碌嘅小辣椒，脾氣火爆，成日用身體撞人，撞親就爆辣椒粉。",
    },
    baseStats: { hp: 36, attack: 11, defense: 7, speed: 13 },
    skills: [
      {
        id: "fiery-temper",
        name: { en: "Fiery Temper", zh: "火爆脾氣" },
        description: {
          en: "Ignites, swells up, and rams the foe in a burst of chilli flame.",
          zh: "全身着火膨脹，向對手猛烈衝撞，爆出辣椒火焰。",
        },
        power: 1.2,
        cooldown: 2,
      },
    ],
    evolvesTo: null,
    evolutionRequirement: null,
    modelUrl: "/models/chilli-baby.glb",
    animUrls: { idle: "/models/chilli-baby-idle.glb", walk: "/models/chilli-baby-walk.glb", attack: "/models/chilli-baby-attack.glb", hit: "/models/chilli-baby-hit.glb" },
    animated: true,
    rigLite: true,
    // facing-lock: 2026-08-01 player-back enemy-face
    modelYaw: -Math.PI / 2,
    modelHeightM: 0.2,
  },
  {
    id: "garlic-guard",
    seriesId: "garlic-guard",
    stage: 1,
    name: { en: "Garlic Guard", zh: "蒜頭衛兵" },
    element: "metal",
    flavor: "spicy",
    rarity: "basic",
    foodOrigin: { en: "Garlic", zh: "蒜頭" },
    description: {
      en: "A plump garlic sentry. Its pungent silver aura keeps germs — and foes — at bay.",
      zh: "肥嘟嘟嘅蒜頭哨兵，一身刺鼻銀光，病菌同敵人都唔敢埋身。",
    },
    baseStats: { hp: 40, attack: 8, defense: 12, speed: 8 },
    skills: [
      {
        id: "antibacterial-shield",
        name: { en: "Antibacterial Shield", zh: "抗菌護盾" },
        description: {
          en: "A silver garlic barrier restores 20% team HP.",
          zh: "銀色蒜香護盾包圍全隊，回復 20% HP。",
        },
        power: 0,
        cooldown: 3,
        healPercent: 0.2,
      },
    ],
    evolvesTo: null,
    evolutionRequirement: null,
    modelUrl: "/models/garlic-guard.glb",
    animUrls: { idle: "/models/garlic-guard-idle.glb", walk: "/models/garlic-guard-walk.glb" },
    animated: true,
    rigLite: true,
    // facing-lock: 2026-08-01 player-back enemy-face
    modelYaw: -Math.PI / 2,
    modelHeightM: 0.2,
  },
  {
    id: "lemongrass-swordsman",
    seriesId: "lemongrass-swordsman",
    stage: 1,
    name: { en: "Lemongrass Swordsman", zh: "香茅劍客" },
    element: "wood",
    flavor: "sour",
    rarity: "basic",
    foodOrigin: { en: "Lemongrass", zh: "香茅" },
    description: {
      en: "A slender duelist who fences with a thin lemongrass blade. Every slash smells of citrus.",
      zh: "身形修長嘅劍客，手持香茅葉細劍，每一斬都帶住清新檸檬香。",
    },
    baseStats: { hp: 34, attack: 12, defense: 7, speed: 15 },
    skills: [
      {
        id: "lemongrass-sword-dance",
        name: { en: "Lemongrass Sword Dance", zh: "香茅劍舞" },
        description: {
          en: "Spins gracefully, tracing green sword arcs as leaves scatter.",
          zh: "優雅旋身劃出翠綠劍光，香茅葉隨劍舞飄落。",
        },
        power: 1.25,
        cooldown: 2,
      },
    ],
    evolvesTo: null,
    evolutionRequirement: null,
    modelUrl: "/models/lemongrass-swordsman.glb",
    animUrls: { idle: "/models/lemongrass-swordsman-idle.glb", walk: "/models/lemongrass-swordsman-walk.glb", attack: "/models/lemongrass-swordsman-attack.glb", hit: "/models/lemongrass-swordsman-hit.glb" },
    animated: true,
    rigLite: true,
    // facing-lock: 2026-08-01 player-back enemy-face
    modelYaw: -Math.PI / 2,
    modelHeightM: 0.26,
  },
  {
    id: "vermicelli-sprite",
    seriesId: "vermicelli-sprite",
    stage: 1,
    name: { en: "Vermicelli Sprite", zh: "米粉精靈" },
    element: "water",
    flavor: "salty",
    rarity: "basic",
    foodOrigin: { en: "Rice Vermicelli", zh: "米粉" },
    description: {
      en: "A wavy sprite of silky rice noodles. Whips its soft body like a lash.",
      zh: "一束柔滑米粉化成嘅小精靈，成條身體甩起嚟好似鞭咁。",
    },
    baseStats: { hp: 36, attack: 10, defense: 8, speed: 14 },
    skills: [
      {
        id: "vermicelli-wrap",
        name: { en: "Vermicelli Wrap", zh: "米粉纏繞" },
        description: {
          en: "Extends noodle tendrils that coil around the foe in a spray of droplets.",
          zh: "伸出多條米粉觸手漩渦式纏實對手，水珠四濺。",
        },
        power: 1.15,
        cooldown: 2,
      },
    ],
    evolvesTo: null,
    evolutionRequirement: null,
    modelUrl: "/models/vermicelli-sprite.glb",
    animated: true,
    rigLite: true,
    // facing-lock: 2026-08-01 player-back enemy-face
    modelYaw: -Math.PI / 2,
    modelHeightM: 0.26,
  },
  {
    id: "egg-guard",
    seriesId: "egg-guard",
    stage: 1,
    name: { en: "Egg Guard", zh: "蛋蛋守衛" },
    element: "earth",
    flavor: "salty",
    rarity: "basic",
    foodOrigin: { en: "Egg", zh: "雞蛋" },
    description: {
      en: "A stout egg wearing its cracked shell as a helmet. Slow but dependable.",
      zh: "戴住爛蛋殼頭盔嘅硬淨蛋蛋，行得慢但係好可靠。",
    },
    baseStats: { hp: 44, attack: 7, defense: 13, speed: 6 },
    skills: [
      {
        id: "yolk-guard",
        name: { en: "Yolk Guard", zh: "蛋黃守護" },
        description: {
          en: "A warm golden yolk shield restores 20% team HP.",
          zh: "溫暖金黃蛋黃護盾守護全隊，回復 20% HP。",
        },
        power: 0,
        cooldown: 3,
        healPercent: 0.2,
      },
    ],
    evolvesTo: null,
    evolutionRequirement: null,
    modelUrl: "/models/egg-guard.glb",
    animUrls: { idle: "/models/egg-guard-idle.glb", walk: "/models/egg-guard-walk.glb", attack: "/models/egg-guard-attack.glb", hit: "/models/egg-guard-hit.glb" },
    animated: true,
    // HQ remake 2026-08-02：封頂網格＋Tripo rigLite（同其他基礎）
    rigLite: true,
    // facing-lock: 2026-08-02 player-back enemy-face
    modelYaw: 0,
    modelHeightM: 0.2,
  },
  {
    id: "shrimp-hopper",
    seriesId: "shrimp-hopper",
    stage: 1,
    name: { en: "Shrimp Hopper", zh: "蝦仔跳跳" },
    element: "water",
    flavor: "sweet",
    rarity: "basic",
    foodOrigin: { en: "Fresh Shrimp", zh: "鮮蝦" },
    description: {
      en: "A springy little shrimp that ricochets off its tail. Never sits still.",
      zh: "用條尾彈嚟彈去嘅小蝦仔，一秒都坐唔定。",
    },
    baseStats: { hp: 33, attack: 11, defense: 6, speed: 16 },
    skills: [
      {
        id: "bubble-shot",
        name: { en: "Bubble Shot", zh: "水泡射擊" },
        description: {
          en: "Sprays a stream of rainbow-sheened bubbles that pop on impact.",
          zh: "連續噴出彩虹光澤水泡，命中即爆成水花。",
        },
        power: 1.15,
        cooldown: 2,
      },
    ],
    evolvesTo: null,
    evolutionRequirement: null,
    modelUrl: "/models/shrimp-hopper.glb",
    animUrls: { idle: "/models/shrimp-hopper-idle.glb", walk: "/models/shrimp-hopper-walk.glb" },
    animated: true,
    rigLite: true,
    // facing-lock: 2026-08-01 player-back enemy-face
    modelYaw: -Math.PI / 2,
    modelHeightM: 0.2,
  },
  {
    id: "nasi-lemak-tot",
    seriesId: "nasi-lemak-squad",
    stage: 1,
    name: { en: "Nasi Lemak Tot", zh: "椰漿飯仔" },
    element: "earth",
    flavor: "spicy",
    rarity: "common",
    foodOrigin: { en: "Nasi Lemak", zh: "椰漿飯" },
    description: {
      en: "A tiny, fragrant lump of coconut rice wrapped snugly in a fresh banana leaf diaper. It toddles around with a single crispy anchovy on its head, spreading a gentle aroma of sweet pandan.",
      zh: "一個散發著椰香的小米飯團，裹在溫馨的芭蕉葉尿布中。它頭上戴著一條香脆的江魚仔，走起路來搖搖晃晃，散發出淡淡的斑蘭清香。",
    },
    baseStats: { hp: 45, attack: 13, defense: 10, speed: 14 },
    skills: [
      {
        id: "nasi-lemak-tot-skill-1",
        name: { en: "Pandan Whiff", zh: "斑蘭飄香" },
        description: { en: "Releases a sweet, soothing aroma of coconut and pandan that disorients opponents while dealing light damage.", zh: "釋放出香甜誘人的椰香斑蘭氣味，迷惑對手並造成輕微傷害。" },
        power: 1,
        cooldown: 0,
      },
      {
        id: "nasi-lemak-tot-skill-2",
        name: { en: "Bilis Bonk", zh: "脆炸江魚撞" },
        description: { en: "Charges forward with a crunchy, hard-hitting headbutt powered by a dried anchovy.", zh: "以爽脆堅硬的江魚仔奮力向前一撞，痛擊前方敵人。" },
        power: 1.4,
        cooldown: 2,
      },
    ],
    evolvesTo: "nasi-lemak-scout",
    evolutionRequirement: {"items":{"nasi-lemak-squad-essence":5},"checkinCentres":2},
    // 圓身飯團：rig 必敗，用靜態 Tripo mesh + 程序化 idle／攻擊
    modelUrl: "/models/nasi-lemak-tot.glb",
    animUrls: { idle: "/models/nasi-lemak-tot-idle.glb", walk: "/models/nasi-lemak-tot-walk.glb" },
    modelHeightM: 0.3,
    animated: true,
    // facing-lock: 2026-08-01 player-back enemy-face
    modelYaw: Math.PI / 2,
  },
  {
    id: "nasi-lemak-scout",
    seriesId: "nasi-lemak-squad",
    stage: 2,
    name: { en: "Nasi Lemak Scout", zh: "椰漿飯小兵" },
    element: "earth",
    flavor: "spicy",
    rarity: "rare",
    foodOrigin: { en: "Nasi Lemak", zh: "椰漿飯" },
    description: {
      en: "Outfitted for backyard adventures, this chubby rice spirit wears a hard-boiled egg slice as a protective helmet and carries a crisp cucumber shield. It is beginning to master the warm, fiery kick of sweet sambal.",
      zh: "裝備齊全的胖嘟嘟冒險小兵，戴著半顆水煮蛋做成的頭盔，手持一片清脆的小黃瓜盾牌。它已經開始學會掌控參巴辣椒醬的溫暖熱力。",
    },
    baseStats: { hp: 72, attack: 22, defense: 18, speed: 20 },
    skills: [
      {
        id: "nasi-lemak-scout-skill-1",
        name: { en: "Cucumber Shield Bash", zh: "青瓜爽脆盾" },
        description: { en: "Slams enemies with a cool, thick cucumber slice that also dampens incoming attacks.", zh: "用清涼厚實的青瓜片猛擊對手，同時抵擋迎面而來的攻勢。" },
        power: 1.1,
        cooldown: 0,
      },
      {
        id: "nasi-lemak-scout-skill-2",
        name: { en: "Sambal Splash", zh: "參巴辣醬擊" },
        description: { en: "Splashes spicy, aromatic sambal chili to inflict continuous burning damage on foes.", zh: "潑灑香辣惹味的參巴辣椒醬，對敵人造成持續的灼燒傷害。" },
        power: 1.7,
        cooldown: 2,
      },
    ],
    evolvesTo: "nasi-lemak-general",
    evolutionRequirement: {"items":{"nasi-lemak-squad-essence":10},"checkinCentres":5},
    modelUrl: "/models/nasi-lemak-scout.glb",
    animUrls: { idle: "/models/nasi-lemak-scout-idle.glb", walk: "/models/nasi-lemak-scout-walk.glb" },
    modelHeightM: 0.5,
    animated: true,
    rigLite: true,
    // facing-lock: 2026-08-01 player-back enemy-face
    modelYaw: -Math.PI / 2,
  },
  {
    id: "nasi-lemak-general",
    seriesId: "nasi-lemak-squad",
    stage: 3,
    name: { en: "Nasi Lemak General", zh: "椰漿飯大將軍" },
    element: "earth",
    flavor: "spicy",
    rarity: "epic",
    foodOrigin: { en: "Nasi Lemak", zh: "椰漿飯" },
    description: {
      en: "The grand defender of the morning markets, draped in a majestic, flowing banana leaf cape. It wields a mighty golden-fried chicken wing as a sword and commands the deep, rich volcano of savory-sweet sambal.",
      zh: "晨間巴剎與熟食中心的偉大捍衛者，身披威武的芭蕉葉斗篷。它手握一隻金黃酥脆的炸雞翅神劍，能召喚出濃郁香辣的參巴火山狂潮。",
    },
    baseStats: { hp: 102, attack: 34, defense: 28, speed: 26 },
    skills: [
      {
        id: "nasi-lemak-general-skill-1",
        name: { en: "Golden Wing Slasher", zh: "酥脆炸雞斬" },
        description: { en: "Slashes through enemy lines with razor-sharp, golden-fried chicken wing blades.", zh: "揮舞利如刀刃的金黃酥脆炸雞翼，無情地橫掃敵陣。" },
        power: 1.2,
        cooldown: 0,
      },
      {
        id: "nasi-lemak-general-skill-2",
        name: { en: "Volcanic Sambal Eruption", zh: "參巴火山爆" },
        description: { en: "Unleashes a devastating geyser of fiery sambal chili that scorches the entire battlefield.", zh: "引爆火山般的烈焰參巴醬，用極致的辛辣火舌吞噬戰場。" },
        power: 2,
        cooldown: 3,
      },
    ],
    evolvesTo: null,
    evolutionRequirement: null,
    modelUrl: "/models/nasi-lemak-general.glb",
    animUrls: { idle: "/models/nasi-lemak-general-idle.glb", walk: "/models/nasi-lemak-general-walk.glb" },
    modelHeightM: 0.65,
    animated: true,
    rigLite: true,
    // facing-lock: 2026-08-01 player-back enemy-face
    modelYaw: -Math.PI / 2,
  },
];

export const SPECIES_MAP: Record<string, Species> = Object.fromEntries(
  SPECIES.map((s) => [s.id, s])
);

export const SERIES_MAP: Record<string, SpeciesSeries> = Object.fromEntries(
  SERIES.map((s) => [s.id, s])
);

/** 未來精靈備份表（概念圖出現但未入 MVP 名單）：沙嗲仙子、咖哩獅、雲吞妖、燒肉魔、蠔煎鬼、沙嗲串兵、金鳳炒粿仙、飛餅神象、辣椒螃蟹王 */
